/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { AppointmentCreateNestedManyWithoutClinicsInput } from "./AppointmentCreateNestedManyWithoutClinicsInput";
import { Type } from "class-transformer";
import { DentalProcedureCreateNestedManyWithoutClinicsInput } from "./DentalProcedureCreateNestedManyWithoutClinicsInput";
import { InvoiceCreateNestedManyWithoutClinicsInput } from "./InvoiceCreateNestedManyWithoutClinicsInput";
import { PatientCreateNestedManyWithoutClinicsInput } from "./PatientCreateNestedManyWithoutClinicsInput";
import { ProfessionalCreateNestedManyWithoutClinicsInput } from "./ProfessionalCreateNestedManyWithoutClinicsInput";
import { UserCreateNestedManyWithoutClinicsInput } from "./UserCreateNestedManyWithoutClinicsInput";

@InputType()
class ClinicCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentCreateNestedManyWithoutClinicsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentCreateNestedManyWithoutClinicsInput)
  @IsOptional()
  @Field(() => AppointmentCreateNestedManyWithoutClinicsInput, {
    nullable: true,
  })
  appointment?: AppointmentCreateNestedManyWithoutClinicsInput;

  @ApiProperty({
    required: false,
    type: () => DentalProcedureCreateNestedManyWithoutClinicsInput,
  })
  @ValidateNested()
  @Type(() => DentalProcedureCreateNestedManyWithoutClinicsInput)
  @IsOptional()
  @Field(() => DentalProcedureCreateNestedManyWithoutClinicsInput, {
    nullable: true,
  })
  dentalProcedure?: DentalProcedureCreateNestedManyWithoutClinicsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceCreateNestedManyWithoutClinicsInput,
  })
  @ValidateNested()
  @Type(() => InvoiceCreateNestedManyWithoutClinicsInput)
  @IsOptional()
  @Field(() => InvoiceCreateNestedManyWithoutClinicsInput, {
    nullable: true,
  })
  invoice?: InvoiceCreateNestedManyWithoutClinicsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  logoUrl?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: false,
    type: () => PatientCreateNestedManyWithoutClinicsInput,
  })
  @ValidateNested()
  @Type(() => PatientCreateNestedManyWithoutClinicsInput)
  @IsOptional()
  @Field(() => PatientCreateNestedManyWithoutClinicsInput, {
    nullable: true,
  })
  patient?: PatientCreateNestedManyWithoutClinicsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
    type: () => ProfessionalCreateNestedManyWithoutClinicsInput,
  })
  @ValidateNested()
  @Type(() => ProfessionalCreateNestedManyWithoutClinicsInput)
  @IsOptional()
  @Field(() => ProfessionalCreateNestedManyWithoutClinicsInput, {
    nullable: true,
  })
  professional?: ProfessionalCreateNestedManyWithoutClinicsInput;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutClinicsInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutClinicsInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutClinicsInput, {
    nullable: true,
  })
  user?: UserCreateNestedManyWithoutClinicsInput;
}

export { ClinicCreateInput as ClinicCreateInput };
