/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ClinicService } from "../clinic.service";
import { ClinicCreateInput } from "./ClinicCreateInput";
import { Clinic } from "./Clinic";
import { ClinicFindManyArgs } from "./ClinicFindManyArgs";
import { ClinicWhereUniqueInput } from "./ClinicWhereUniqueInput";
import { ClinicUpdateInput } from "./ClinicUpdateInput";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { AppointmentWhereUniqueInput } from "../../appointment/base/AppointmentWhereUniqueInput";
import { DentalProcedureFindManyArgs } from "../../dentalProcedure/base/DentalProcedureFindManyArgs";
import { DentalProcedure } from "../../dentalProcedure/base/DentalProcedure";
import { DentalProcedureWhereUniqueInput } from "../../dentalProcedure/base/DentalProcedureWhereUniqueInput";
import { InvoiceFindManyArgs } from "../../invoice/base/InvoiceFindManyArgs";
import { Invoice } from "../../invoice/base/Invoice";
import { InvoiceWhereUniqueInput } from "../../invoice/base/InvoiceWhereUniqueInput";
import { PatientFindManyArgs } from "../../patient/base/PatientFindManyArgs";
import { Patient } from "../../patient/base/Patient";
import { PatientWhereUniqueInput } from "../../patient/base/PatientWhereUniqueInput";
import { ProfessionalFindManyArgs } from "../../professional/base/ProfessionalFindManyArgs";
import { Professional } from "../../professional/base/Professional";
import { ProfessionalWhereUniqueInput } from "../../professional/base/ProfessionalWhereUniqueInput";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

export class ClinicControllerBase {
  constructor(protected readonly service: ClinicService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Clinic })
  async createClinic(@common.Body() data: ClinicCreateInput): Promise<Clinic> {
    return await this.service.createClinic({
      data: data,
      select: {
        address: true,
        createdAt: true,
        email: true,
        id: true,
        logoUrl: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Clinic] })
  @ApiNestedQuery(ClinicFindManyArgs)
  async clinics(@common.Req() request: Request): Promise<Clinic[]> {
    const args = plainToClass(ClinicFindManyArgs, request.query);
    return this.service.clinics({
      ...args,
      select: {
        address: true,
        createdAt: true,
        email: true,
        id: true,
        logoUrl: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Clinic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async clinic(
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<Clinic | null> {
    const result = await this.service.clinic({
      where: params,
      select: {
        address: true,
        createdAt: true,
        email: true,
        id: true,
        logoUrl: true,
        name: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Clinic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateClinic(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() data: ClinicUpdateInput
  ): Promise<Clinic | null> {
    try {
      return await this.service.updateClinic({
        where: params,
        data: data,
        select: {
          address: true,
          createdAt: true,
          email: true,
          id: true,
          logoUrl: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Clinic })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteClinic(
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<Clinic | null> {
    try {
      return await this.service.deleteClinic({
        where: params,
        select: {
          address: true,
          createdAt: true,
          email: true,
          id: true,
          logoUrl: true,
          name: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/appointment")
  @ApiNestedQuery(AppointmentFindManyArgs)
  async findAppointment(
    @common.Req() request: Request,
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<Appointment[]> {
    const query = plainToClass(AppointmentFindManyArgs, request.query);
    const results = await this.service.findAppointment(params.id, {
      ...query,
      select: {
        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endTime: true,
        id: true,
        notes: true,

        patient: {
          select: {
            id: true,
          },
        },

        professional: {
          select: {
            id: true,
          },
        },

        reason: true,
        startTime: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appointment")
  async connectAppointment(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        connect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appointment")
  async updateAppointment(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        set: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appointment")
  async disconnectAppointment(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        disconnect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/dentalProcedure")
  @ApiNestedQuery(DentalProcedureFindManyArgs)
  async findDentalProcedure(
    @common.Req() request: Request,
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<DentalProcedure[]> {
    const query = plainToClass(DentalProcedureFindManyArgs, request.query);
    const results = await this.service.findDentalProcedure(params.id, {
      ...query,
      select: {
        active: true,
        basePrice: true,

        clinic: {
          select: {
            id: true,
          },
        },

        code: true,
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dentalProcedure")
  async connectDentalProcedure(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: DentalProcedureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedure: {
        connect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dentalProcedure")
  async updateDentalProcedure(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: DentalProcedureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedure: {
        set: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dentalProcedure")
  async disconnectDentalProcedure(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: DentalProcedureWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedure: {
        disconnect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/invoice")
  @ApiNestedQuery(InvoiceFindManyArgs)
  async findInvoice(
    @common.Req() request: Request,
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<Invoice[]> {
    const query = plainToClass(InvoiceFindManyArgs, request.query);
    const results = await this.service.findInvoice(params.id, {
      ...query,
      select: {
        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,
        notes: true,

        patient: {
          select: {
            id: true,
          },
        },

        status: true,
        totalAmount: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/invoice")
  async connectInvoice(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoice: {
        connect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/invoice")
  async updateInvoice(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoice: {
        set: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/invoice")
  async disconnectInvoice(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoice: {
        disconnect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/patient")
  @ApiNestedQuery(PatientFindManyArgs)
  async findPatient(
    @common.Req() request: Request,
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<Patient[]> {
    const query = plainToClass(PatientFindManyArgs, request.query);
    const results = await this.service.findPatient(params.id, {
      ...query,
      select: {
        address: true,
        birthDate: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dni: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,

        medicalRecord: {
          select: {
            id: true,
          },
        },

        odontogram: {
          select: {
            id: true,
          },
        },

        phone: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/patient")
  async connectPatient(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: PatientWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      patient: {
        connect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/patient")
  async updatePatient(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: PatientWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      patient: {
        set: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/patient")
  async disconnectPatient(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: PatientWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      patient: {
        disconnect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/professional")
  @ApiNestedQuery(ProfessionalFindManyArgs)
  async findProfessional(
    @common.Req() request: Request,
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<Professional[]> {
    const query = plainToClass(ProfessionalFindManyArgs, request.query);
    const results = await this.service.findProfessional(params.id, {
      ...query,
      select: {
        active: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        license: true,
        phone: true,
        speciality: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/professional")
  async connectProfessional(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: ProfessionalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      professional: {
        connect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/professional")
  async updateProfessional(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: ProfessionalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      professional: {
        set: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/professional")
  async disconnectProfessional(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: ProfessionalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      professional: {
        disconnect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/user")
  @ApiNestedQuery(UserFindManyArgs)
  async findUser(
    @common.Req() request: Request,
    @common.Param() params: ClinicWhereUniqueInput
  ): Promise<User[]> {
    const query = plainToClass(UserFindManyArgs, request.query);
    const results = await this.service.findUser(params.id, {
      ...query,
      select: {
        active: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        password: true,

        professional: {
          select: {
            id: true,
          },
        },

        role: true,
        updatedAt: true,
        username: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/user")
  async connectUser(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      user: {
        connect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/user")
  async updateUser(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      user: {
        set: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/user")
  async disconnectUser(
    @common.Param() params: ClinicWhereUniqueInput,
    @common.Body() body: UserWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      user: {
        disconnect: body,
      },
    };
    await this.service.updateClinic({
      where: params,
      data,
      select: { id: true },
    });
  }
}
