/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Clinic } from "./Clinic";
import { ClinicCountArgs } from "./ClinicCountArgs";
import { ClinicFindManyArgs } from "./ClinicFindManyArgs";
import { ClinicFindUniqueArgs } from "./ClinicFindUniqueArgs";
import { CreateClinicArgs } from "./CreateClinicArgs";
import { UpdateClinicArgs } from "./UpdateClinicArgs";
import { DeleteClinicArgs } from "./DeleteClinicArgs";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { DentalProcedureFindManyArgs } from "../../dentalProcedure/base/DentalProcedureFindManyArgs";
import { DentalProcedure } from "../../dentalProcedure/base/DentalProcedure";
import { InvoiceFindManyArgs } from "../../invoice/base/InvoiceFindManyArgs";
import { Invoice } from "../../invoice/base/Invoice";
import { PatientFindManyArgs } from "../../patient/base/PatientFindManyArgs";
import { Patient } from "../../patient/base/Patient";
import { ProfessionalFindManyArgs } from "../../professional/base/ProfessionalFindManyArgs";
import { Professional } from "../../professional/base/Professional";
import { UserFindManyArgs } from "../../user/base/UserFindManyArgs";
import { User } from "../../user/base/User";
import { ClinicService } from "../clinic.service";
@graphql.Resolver(() => Clinic)
export class ClinicResolverBase {
  constructor(protected readonly service: ClinicService) {}

  async _clinicsMeta(
    @graphql.Args() args: ClinicCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Clinic])
  async clinics(@graphql.Args() args: ClinicFindManyArgs): Promise<Clinic[]> {
    return this.service.clinics(args);
  }

  @graphql.Query(() => Clinic, { nullable: true })
  async clinic(
    @graphql.Args() args: ClinicFindUniqueArgs
  ): Promise<Clinic | null> {
    const result = await this.service.clinic(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Clinic)
  async createClinic(@graphql.Args() args: CreateClinicArgs): Promise<Clinic> {
    return await this.service.createClinic({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Clinic)
  async updateClinic(
    @graphql.Args() args: UpdateClinicArgs
  ): Promise<Clinic | null> {
    try {
      return await this.service.updateClinic({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Clinic)
  async deleteClinic(
    @graphql.Args() args: DeleteClinicArgs
  ): Promise<Clinic | null> {
    try {
      return await this.service.deleteClinic(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Appointment], { name: "appointment" })
  async findAppointment(
    @graphql.Parent() parent: Clinic,
    @graphql.Args() args: AppointmentFindManyArgs
  ): Promise<Appointment[]> {
    const results = await this.service.findAppointment(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [DentalProcedure], { name: "dentalProcedure" })
  async findDentalProcedure(
    @graphql.Parent() parent: Clinic,
    @graphql.Args() args: DentalProcedureFindManyArgs
  ): Promise<DentalProcedure[]> {
    const results = await this.service.findDentalProcedure(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Invoice], { name: "invoice" })
  async findInvoice(
    @graphql.Parent() parent: Clinic,
    @graphql.Args() args: InvoiceFindManyArgs
  ): Promise<Invoice[]> {
    const results = await this.service.findInvoice(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Patient], { name: "patient" })
  async findPatient(
    @graphql.Parent() parent: Clinic,
    @graphql.Args() args: PatientFindManyArgs
  ): Promise<Patient[]> {
    const results = await this.service.findPatient(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Professional], { name: "professional" })
  async findProfessional(
    @graphql.Parent() parent: Clinic,
    @graphql.Args() args: ProfessionalFindManyArgs
  ): Promise<Professional[]> {
    const results = await this.service.findProfessional(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [User], { name: "user" })
  async findUser(
    @graphql.Parent() parent: Clinic,
    @graphql.Args() args: UserFindManyArgs
  ): Promise<User[]> {
    const results = await this.service.findUser(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
