/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { DentalProcedureWhereUniqueInput } from "../../dentalProcedure/base/DentalProcedureWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsInt,
  Max,
  IsNumber,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { InvoiceWhereUniqueInput } from "../../invoice/base/InvoiceWhereUniqueInput";
import { TreatmentWhereUniqueInput } from "../../treatment/base/TreatmentWhereUniqueInput";

@InputType()
class InvoiceItemUpdateInput {
  @ApiProperty({
    required: false,
    type: () => DentalProcedureWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DentalProcedureWhereUniqueInput)
  @IsOptional()
  @Field(() => DentalProcedureWhereUniqueInput, {
    nullable: true,
  })
  dentalProcedure?: DentalProcedureWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => InvoiceWhereUniqueInput)
  @IsOptional()
  @Field(() => InvoiceWhereUniqueInput, {
    nullable: true,
  })
  invoice?: InvoiceWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  quantity?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  total?: number;

  @ApiProperty({
    required: false,
    type: () => TreatmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TreatmentWhereUniqueInput)
  @IsOptional()
  @Field(() => TreatmentWhereUniqueInput, {
    nullable: true,
  })
  treatment?: TreatmentWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  unitPrice?: number;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date;
}

export { InvoiceItemUpdateInput as InvoiceItemUpdateInput };
