/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
  MaxLength,
  IsEnum,
  IsDate,
} from "class-validator";
import { AuditLogUpdateManyWithoutUsersInput } from "./AuditLogUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";
import { ProfessionalWhereUniqueInput } from "../../professional/base/ProfessionalWhereUniqueInput";
import { RefreshTokenUpdateManyWithoutUsersInput } from "./RefreshTokenUpdateManyWithoutUsersInput";
import { EnumUserRole } from "./EnumUserRole";

@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  active?: boolean;

  @ApiProperty({
    required: false,
    type: () => AuditLogUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AuditLogUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AuditLogUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  auditLog?: AuditLogUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: () => ProfessionalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProfessionalWhereUniqueInput)
  @IsOptional()
  @Field(() => ProfessionalWhereUniqueInput, {
    nullable: true,
  })
  professional?: ProfessionalWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => RefreshTokenUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RefreshTokenUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RefreshTokenUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  refreshToken?: RefreshTokenUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    enum: EnumUserRole,
  })
  @IsEnum(EnumUserRole)
  @IsOptional()
  @Field(() => EnumUserRole, {
    nullable: true,
  })
  role?:
    | "ADMIN"
    | "PROFESSIONAL"
    | "RECEPTIONIST"
    | "VIEWER"
    | "DENTIST"
    | "ASSISTANT"
    | "DOCTOR"
    | "USER";

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}

export { UserUpdateInput as UserUpdateInput };
