/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
  IsDate,
} from "class-validator";
import { AuditLogCreateNestedManyWithoutUsersInput } from "./AuditLogCreateNestedManyWithoutUsersInput";
import { Type } from "class-transformer";
import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";
import { ProfessionalWhereUniqueInput } from "../../professional/base/ProfessionalWhereUniqueInput";
import { RefreshTokenCreateNestedManyWithoutUsersInput } from "./RefreshTokenCreateNestedManyWithoutUsersInput";
import { EnumUserRole } from "./EnumUserRole";

@InputType()
class UserCreateInput {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  active!: boolean;

  @ApiProperty({
    required: false,
    type: () => AuditLogCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => AuditLogCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => AuditLogCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  auditLog?: AuditLogCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => ProfessionalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProfessionalWhereUniqueInput)
  @IsOptional()
  @Field(() => ProfessionalWhereUniqueInput, {
    nullable: true,
  })
  professional?: ProfessionalWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => RefreshTokenCreateNestedManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => RefreshTokenCreateNestedManyWithoutUsersInput)
  @IsOptional()
  @Field(() => RefreshTokenCreateNestedManyWithoutUsersInput, {
    nullable: true,
  })
  refreshToken?: RefreshTokenCreateNestedManyWithoutUsersInput;

  @ApiProperty({
    required: true,
    enum: EnumUserRole,
  })
  @IsEnum(EnumUserRole)
  @Field(() => EnumUserRole)
  role!:
    | "ADMIN"
    | "PROFESSIONAL"
    | "RECEPTIONIST"
    | "VIEWER"
    | "DENTIST"
    | "ASSISTANT"
    | "DOCTOR"
    | "USER";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  username!: string;
}

export { UserCreateInput as UserCreateInput };
