/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsInt,
  IsEnum,
} from "class-validator";

import { AuditLog } from "../../auditLog/base/AuditLog";
import { Type } from "class-transformer";
import { Clinic } from "../../clinic/base/Clinic";
import { Professional } from "../../professional/base/Professional";
import { RefreshToken } from "../../refreshToken/base/RefreshToken";
import { EnumUserRole } from "./EnumUserRole";

@ObjectType()
class User {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  active!: boolean;

  @ApiProperty({
    required: false,
    type: () => [AuditLog],
  })
  @ValidateNested()
  @Type(() => AuditLog)
  @IsOptional()
  auditLog?: Array<AuditLog>;

  @ApiProperty({
    required: false,
    type: () => Clinic,
  })
  @ValidateNested()
  @Type(() => Clinic)
  @IsOptional()
  clinic?: Clinic | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName!: string | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName!: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  password!: string;

  @ApiProperty({
    required: false,
    type: () => Professional,
  })
  @ValidateNested()
  @Type(() => Professional)
  @IsOptional()
  professional?: Professional | null;

  @ApiProperty({
    required: false,
    type: () => [RefreshToken],
  })
  @ValidateNested()
  @Type(() => RefreshToken)
  @IsOptional()
  refreshToken?: Array<RefreshToken>;

  @ApiProperty({
    required: true,
    enum: EnumUserRole,
  })
  @IsEnum(EnumUserRole)
  @Field(() => EnumUserRole, {
    nullable: true,
  })
  role?:
    | "ADMIN"
    | "PROFESSIONAL"
    | "RECEPTIONIST"
    | "VIEWER"
    | "DENTIST"
    | "ASSISTANT"
    | "DOCTOR"
    | "USER";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  username!: string;
}

export { User as User };
