/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { UserService } from "../user.service";
import { UserCreateInput } from "./UserCreateInput";
import { User } from "./User";
import { UserFindManyArgs } from "./UserFindManyArgs";
import { UserWhereUniqueInput } from "./UserWhereUniqueInput";
import { UserUpdateInput } from "./UserUpdateInput";
import { AuditLogFindManyArgs } from "../../auditLog/base/AuditLogFindManyArgs";
import { AuditLog } from "../../auditLog/base/AuditLog";
import { AuditLogWhereUniqueInput } from "../../auditLog/base/AuditLogWhereUniqueInput";
import { RefreshTokenFindManyArgs } from "../../refreshToken/base/RefreshTokenFindManyArgs";
import { RefreshToken } from "../../refreshToken/base/RefreshToken";
import { RefreshTokenWhereUniqueInput } from "../../refreshToken/base/RefreshTokenWhereUniqueInput";

export class UserControllerBase {
  constructor(protected readonly service: UserService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: User })
  async createUser(@common.Body() data: UserCreateInput): Promise<User> {
    return await this.service.createUser({
      data: {
        ...data,

        clinic: data.clinic
          ? {
              connect: data.clinic,
            }
          : undefined,

        professional: data.professional
          ? {
              connect: data.professional,
            }
          : undefined,
      },
      select: {
        active: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        password: true,

        professional: {
          select: {
            id: true,
          },
        },

        role: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [User] })
  @ApiNestedQuery(UserFindManyArgs)
  async users(@common.Req() request: Request): Promise<User[]> {
    const args = plainToClass(UserFindManyArgs, request.query);
    return this.service.users({
      ...args,
      select: {
        active: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        password: true,

        professional: {
          select: {
            id: true,
          },
        },

        role: true,
        updatedAt: true,
        username: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async user(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    const result = await this.service.user({
      where: params,
      select: {
        active: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        firstName: true,
        id: true,
        lastName: true,
        password: true,

        professional: {
          select: {
            id: true,
          },
        },

        role: true,
        updatedAt: true,
        username: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateUser(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() data: UserUpdateInput
  ): Promise<User | null> {
    try {
      return await this.service.updateUser({
        where: params,
        data: {
          ...data,

          clinic: data.clinic
            ? {
                connect: data.clinic,
              }
            : undefined,

          professional: data.professional
            ? {
                connect: data.professional,
              }
            : undefined,
        },
        select: {
          active: true,

          clinic: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          firstName: true,
          id: true,
          lastName: true,
          password: true,

          professional: {
            select: {
              id: true,
            },
          },

          role: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: User })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteUser(
    @common.Param() params: UserWhereUniqueInput
  ): Promise<User | null> {
    try {
      return await this.service.deleteUser({
        where: params,
        select: {
          active: true,

          clinic: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          firstName: true,
          id: true,
          lastName: true,
          password: true,

          professional: {
            select: {
              id: true,
            },
          },

          role: true,
          updatedAt: true,
          username: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/auditLog")
  @ApiNestedQuery(AuditLogFindManyArgs)
  async findAuditLog(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<AuditLog[]> {
    const query = plainToClass(AuditLogFindManyArgs, request.query);
    const results = await this.service.findAuditLog(params.id, {
      ...query,
      select: {
        action: true,
        createdAt: true,
        fieldField: true,
        id: true,
        newValue: true,
        oldValue: true,
        recordId: true,
        tableName: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/auditLog")
  async connectAuditLog(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLog: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/auditLog")
  async updateAuditLog(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLog: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/auditLog")
  async disconnectAuditLog(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: AuditLogWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      auditLog: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/refreshToken")
  @ApiNestedQuery(RefreshTokenFindManyArgs)
  async findRefreshToken(
    @common.Req() request: Request,
    @common.Param() params: UserWhereUniqueInput
  ): Promise<RefreshToken[]> {
    const query = plainToClass(RefreshTokenFindManyArgs, request.query);
    const results = await this.service.findRefreshToken(params.id, {
      ...query,
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        token: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/refreshToken")
  async connectRefreshToken(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: RefreshTokenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      refreshToken: {
        connect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/refreshToken")
  async updateRefreshToken(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: RefreshTokenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      refreshToken: {
        set: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/refreshToken")
  async disconnectRefreshToken(
    @common.Param() params: UserWhereUniqueInput,
    @common.Body() body: RefreshTokenWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      refreshToken: {
        disconnect: body,
      },
    };
    await this.service.updateUser({
      where: params,
      data,
      select: { id: true },
    });
  }
}
