/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  OdontogramEntry as PrismaOdontogramEntry,
  Odontogram as PrismaOdontogram,
} from "@prisma/client";

export class OdontogramEntryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.OdontogramEntryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.odontogramEntry.count(args);
  }

  async odontogramEntries(
    args: Prisma.OdontogramEntryFindManyArgs
  ): Promise<PrismaOdontogramEntry[]> {
    return this.prisma.odontogramEntry.findMany(args);
  }
  async odontogramEntry(
    args: Prisma.OdontogramEntryFindUniqueArgs
  ): Promise<PrismaOdontogramEntry | null> {
    return this.prisma.odontogramEntry.findUnique(args);
  }
  async createOdontogramEntry(
    args: Prisma.OdontogramEntryCreateArgs
  ): Promise<PrismaOdontogramEntry> {
    return this.prisma.odontogramEntry.create(args);
  }
  async updateOdontogramEntry(
    args: Prisma.OdontogramEntryUpdateArgs
  ): Promise<PrismaOdontogramEntry> {
    return this.prisma.odontogramEntry.update(args);
  }
  async deleteOdontogramEntry(
    args: Prisma.OdontogramEntryDeleteArgs
  ): Promise<PrismaOdontogramEntry> {
    return this.prisma.odontogramEntry.delete(args);
  }

  async getOdontogram(parentId: number): Promise<PrismaOdontogram | null> {
    return this.prisma.odontogramEntry
      .findUnique({
        where: { id: parentId },
      })
      .odontogram();
  }
}
