/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { OdontogramEntry } from "./OdontogramEntry";
import { OdontogramEntryCountArgs } from "./OdontogramEntryCountArgs";
import { OdontogramEntryFindManyArgs } from "./OdontogramEntryFindManyArgs";
import { OdontogramEntryFindUniqueArgs } from "./OdontogramEntryFindUniqueArgs";
import { CreateOdontogramEntryArgs } from "./CreateOdontogramEntryArgs";
import { UpdateOdontogramEntryArgs } from "./UpdateOdontogramEntryArgs";
import { DeleteOdontogramEntryArgs } from "./DeleteOdontogramEntryArgs";
import { Odontogram } from "../../odontogram/base/Odontogram";
import { OdontogramEntryService } from "../odontogramEntry.service";
@graphql.Resolver(() => OdontogramEntry)
export class OdontogramEntryResolverBase {
  constructor(protected readonly service: OdontogramEntryService) {}

  async _odontogramEntriesMeta(
    @graphql.Args() args: OdontogramEntryCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [OdontogramEntry])
  async odontogramEntries(
    @graphql.Args() args: OdontogramEntryFindManyArgs
  ): Promise<OdontogramEntry[]> {
    return this.service.odontogramEntries(args);
  }

  @graphql.Query(() => OdontogramEntry, { nullable: true })
  async odontogramEntry(
    @graphql.Args() args: OdontogramEntryFindUniqueArgs
  ): Promise<OdontogramEntry | null> {
    const result = await this.service.odontogramEntry(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => OdontogramEntry)
  async createOdontogramEntry(
    @graphql.Args() args: CreateOdontogramEntryArgs
  ): Promise<OdontogramEntry> {
    return await this.service.createOdontogramEntry({
      ...args,
      data: {
        ...args.data,

        odontogram: {
          connect: args.data.odontogram,
        },
      },
    });
  }

  @graphql.Mutation(() => OdontogramEntry)
  async updateOdontogramEntry(
    @graphql.Args() args: UpdateOdontogramEntryArgs
  ): Promise<OdontogramEntry | null> {
    try {
      return await this.service.updateOdontogramEntry({
        ...args,
        data: {
          ...args.data,

          odontogram: {
            connect: args.data.odontogram,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => OdontogramEntry)
  async deleteOdontogramEntry(
    @graphql.Args() args: DeleteOdontogramEntryArgs
  ): Promise<OdontogramEntry | null> {
    try {
      return await this.service.deleteOdontogramEntry(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Odontogram, {
    nullable: true,
    name: "odontogram",
  })
  async getOdontogram(
    @graphql.Parent() parent: OdontogramEntry
  ): Promise<Odontogram | null> {
    const result = await this.service.getOdontogram(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
