/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OdontogramEntryService } from "../odontogramEntry.service";
import { OdontogramEntryCreateInput } from "./OdontogramEntryCreateInput";
import { OdontogramEntry } from "./OdontogramEntry";
import { OdontogramEntryFindManyArgs } from "./OdontogramEntryFindManyArgs";
import { OdontogramEntryWhereUniqueInput } from "./OdontogramEntryWhereUniqueInput";
import { OdontogramEntryUpdateInput } from "./OdontogramEntryUpdateInput";

export class OdontogramEntryControllerBase {
  constructor(protected readonly service: OdontogramEntryService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: OdontogramEntry })
  async createOdontogramEntry(
    @common.Body() data: OdontogramEntryCreateInput
  ): Promise<OdontogramEntry> {
    return await this.service.createOdontogramEntry({
      data: {
        ...data,

        odontogram: {
          connect: data.odontogram,
        },
      },
      select: {
        color: true,
        conditionType: true,
        createdAt: true,
        id: true,
        notes: true,

        odontogram: {
          select: {
            id: true,
          },
        },

        surface: true,
        tooth: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [OdontogramEntry] })
  @ApiNestedQuery(OdontogramEntryFindManyArgs)
  async odontogramEntries(
    @common.Req() request: Request
  ): Promise<OdontogramEntry[]> {
    const args = plainToClass(OdontogramEntryFindManyArgs, request.query);
    return this.service.odontogramEntries({
      ...args,
      select: {
        color: true,
        conditionType: true,
        createdAt: true,
        id: true,
        notes: true,

        odontogram: {
          select: {
            id: true,
          },
        },

        surface: true,
        tooth: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: OdontogramEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async odontogramEntry(
    @common.Param() params: OdontogramEntryWhereUniqueInput
  ): Promise<OdontogramEntry | null> {
    const result = await this.service.odontogramEntry({
      where: params,
      select: {
        color: true,
        conditionType: true,
        createdAt: true,
        id: true,
        notes: true,

        odontogram: {
          select: {
            id: true,
          },
        },

        surface: true,
        tooth: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: OdontogramEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOdontogramEntry(
    @common.Param() params: OdontogramEntryWhereUniqueInput,
    @common.Body() data: OdontogramEntryUpdateInput
  ): Promise<OdontogramEntry | null> {
    try {
      return await this.service.updateOdontogramEntry({
        where: params,
        data: {
          ...data,

          odontogram: {
            connect: data.odontogram,
          },
        },
        select: {
          color: true,
          conditionType: true,
          createdAt: true,
          id: true,
          notes: true,

          odontogram: {
            select: {
              id: true,
            },
          },

          surface: true,
          tooth: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: OdontogramEntry })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOdontogramEntry(
    @common.Param() params: OdontogramEntryWhereUniqueInput
  ): Promise<OdontogramEntry | null> {
    try {
      return await this.service.deleteOdontogramEntry({
        where: params,
        select: {
          color: true,
          conditionType: true,
          createdAt: true,
          id: true,
          notes: true,

          odontogram: {
            select: {
              id: true,
            },
          },

          surface: true,
          tooth: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
