/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { MedicalRecord } from "./MedicalRecord";
import { MedicalRecordCountArgs } from "./MedicalRecordCountArgs";
import { MedicalRecordFindManyArgs } from "./MedicalRecordFindManyArgs";
import { MedicalRecordFindUniqueArgs } from "./MedicalRecordFindUniqueArgs";
import { CreateMedicalRecordArgs } from "./CreateMedicalRecordArgs";
import { UpdateMedicalRecordArgs } from "./UpdateMedicalRecordArgs";
import { DeleteMedicalRecordArgs } from "./DeleteMedicalRecordArgs";
import { Patient } from "../../patient/base/Patient";
import { MedicalRecordService } from "../medicalRecord.service";
@graphql.Resolver(() => MedicalRecord)
export class MedicalRecordResolverBase {
  constructor(protected readonly service: MedicalRecordService) {}

  async _medicalRecordsMeta(
    @graphql.Args() args: MedicalRecordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [MedicalRecord])
  async medicalRecords(
    @graphql.Args() args: MedicalRecordFindManyArgs
  ): Promise<MedicalRecord[]> {
    return this.service.medicalRecords(args);
  }

  @graphql.Query(() => MedicalRecord, { nullable: true })
  async medicalRecord(
    @graphql.Args() args: MedicalRecordFindUniqueArgs
  ): Promise<MedicalRecord | null> {
    const result = await this.service.medicalRecord(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => MedicalRecord)
  async createMedicalRecord(
    @graphql.Args() args: CreateMedicalRecordArgs
  ): Promise<MedicalRecord> {
    return await this.service.createMedicalRecord({
      ...args,
      data: {
        ...args.data,

        patient: {
          connect: args.data.patient,
        },
      },
    });
  }

  @graphql.Mutation(() => MedicalRecord)
  async updateMedicalRecord(
    @graphql.Args() args: UpdateMedicalRecordArgs
  ): Promise<MedicalRecord | null> {
    try {
      return await this.service.updateMedicalRecord({
        ...args,
        data: {
          ...args.data,

          patient: {
            connect: args.data.patient,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => MedicalRecord)
  async deleteMedicalRecord(
    @graphql.Args() args: DeleteMedicalRecordArgs
  ): Promise<MedicalRecord | null> {
    try {
      return await this.service.deleteMedicalRecord(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => Patient, {
    nullable: true,
    name: "patient",
  })
  async getPatient(
    @graphql.Parent() parent: MedicalRecord
  ): Promise<Patient | null> {
    const result = await this.service.getPatient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
