/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DentalProcedurePriceService } from "../dentalProcedurePrice.service";
import { DentalProcedurePriceCreateInput } from "./DentalProcedurePriceCreateInput";
import { DentalProcedurePrice } from "./DentalProcedurePrice";
import { DentalProcedurePriceFindManyArgs } from "./DentalProcedurePriceFindManyArgs";
import { DentalProcedurePriceWhereUniqueInput } from "./DentalProcedurePriceWhereUniqueInput";
import { DentalProcedurePriceUpdateInput } from "./DentalProcedurePriceUpdateInput";

export class DentalProcedurePriceControllerBase {
  constructor(protected readonly service: DentalProcedurePriceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DentalProcedurePrice })
  async createDentalProcedurePrice(
    @common.Body() data: DentalProcedurePriceCreateInput
  ): Promise<DentalProcedurePrice> {
    return await this.service.createDentalProcedurePrice({
      data: {
        ...data,

        dentalProcedure: {
          connect: data.dentalProcedure,
        },

        healthInsurance: {
          connect: data.healthInsurance,
        },
      },
      select: {
        createdAt: true,

        dentalProcedure: {
          select: {
            id: true,
          },
        },

        healthInsurance: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DentalProcedurePrice] })
  @ApiNestedQuery(DentalProcedurePriceFindManyArgs)
  async dentalProcedurePrices(
    @common.Req() request: Request
  ): Promise<DentalProcedurePrice[]> {
    const args = plainToClass(DentalProcedurePriceFindManyArgs, request.query);
    return this.service.dentalProcedurePrices({
      ...args,
      select: {
        createdAt: true,

        dentalProcedure: {
          select: {
            id: true,
          },
        },

        healthInsurance: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DentalProcedurePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async dentalProcedurePrice(
    @common.Param() params: DentalProcedurePriceWhereUniqueInput
  ): Promise<DentalProcedurePrice | null> {
    const result = await this.service.dentalProcedurePrice({
      where: params,
      select: {
        createdAt: true,

        dentalProcedure: {
          select: {
            id: true,
          },
        },

        healthInsurance: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DentalProcedurePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDentalProcedurePrice(
    @common.Param() params: DentalProcedurePriceWhereUniqueInput,
    @common.Body() data: DentalProcedurePriceUpdateInput
  ): Promise<DentalProcedurePrice | null> {
    try {
      return await this.service.updateDentalProcedurePrice({
        where: params,
        data: {
          ...data,

          dentalProcedure: {
            connect: data.dentalProcedure,
          },

          healthInsurance: {
            connect: data.healthInsurance,
          },
        },
        select: {
          createdAt: true,

          dentalProcedure: {
            select: {
              id: true,
            },
          },

          healthInsurance: {
            select: {
              id: true,
            },
          },

          id: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DentalProcedurePrice })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDentalProcedurePrice(
    @common.Param() params: DentalProcedurePriceWhereUniqueInput
  ): Promise<DentalProcedurePrice | null> {
    try {
      return await this.service.deleteDentalProcedurePrice({
        where: params,
        select: {
          createdAt: true,

          dentalProcedure: {
            select: {
              id: true,
            },
          },

          healthInsurance: {
            select: {
              id: true,
            },
          },

          id: true,
          price: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
