/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DentalProcedurePrice } from "./DentalProcedurePrice";
import { DentalProcedurePriceCountArgs } from "./DentalProcedurePriceCountArgs";
import { DentalProcedurePriceFindManyArgs } from "./DentalProcedurePriceFindManyArgs";
import { DentalProcedurePriceFindUniqueArgs } from "./DentalProcedurePriceFindUniqueArgs";
import { CreateDentalProcedurePriceArgs } from "./CreateDentalProcedurePriceArgs";
import { UpdateDentalProcedurePriceArgs } from "./UpdateDentalProcedurePriceArgs";
import { DeleteDentalProcedurePriceArgs } from "./DeleteDentalProcedurePriceArgs";
import { DentalProcedure } from "../../dentalProcedure/base/DentalProcedure";
import { HealthInsurance } from "../../healthInsurance/base/HealthInsurance";
import { DentalProcedurePriceService } from "../dentalProcedurePrice.service";
@graphql.Resolver(() => DentalProcedurePrice)
export class DentalProcedurePriceResolverBase {
  constructor(protected readonly service: DentalProcedurePriceService) {}

  async _dentalProcedurePricesMeta(
    @graphql.Args() args: DentalProcedurePriceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DentalProcedurePrice])
  async dentalProcedurePrices(
    @graphql.Args() args: DentalProcedurePriceFindManyArgs
  ): Promise<DentalProcedurePrice[]> {
    return this.service.dentalProcedurePrices(args);
  }

  @graphql.Query(() => DentalProcedurePrice, { nullable: true })
  async dentalProcedurePrice(
    @graphql.Args() args: DentalProcedurePriceFindUniqueArgs
  ): Promise<DentalProcedurePrice | null> {
    const result = await this.service.dentalProcedurePrice(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DentalProcedurePrice)
  async createDentalProcedurePrice(
    @graphql.Args() args: CreateDentalProcedurePriceArgs
  ): Promise<DentalProcedurePrice> {
    return await this.service.createDentalProcedurePrice({
      ...args,
      data: {
        ...args.data,

        dentalProcedure: {
          connect: args.data.dentalProcedure,
        },

        healthInsurance: {
          connect: args.data.healthInsurance,
        },
      },
    });
  }

  @graphql.Mutation(() => DentalProcedurePrice)
  async updateDentalProcedurePrice(
    @graphql.Args() args: UpdateDentalProcedurePriceArgs
  ): Promise<DentalProcedurePrice | null> {
    try {
      return await this.service.updateDentalProcedurePrice({
        ...args,
        data: {
          ...args.data,

          dentalProcedure: {
            connect: args.data.dentalProcedure,
          },

          healthInsurance: {
            connect: args.data.healthInsurance,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DentalProcedurePrice)
  async deleteDentalProcedurePrice(
    @graphql.Args() args: DeleteDentalProcedurePriceArgs
  ): Promise<DentalProcedurePrice | null> {
    try {
      return await this.service.deleteDentalProcedurePrice(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => DentalProcedure, {
    nullable: true,
    name: "dentalProcedure",
  })
  async getDentalProcedure(
    @graphql.Parent() parent: DentalProcedurePrice
  ): Promise<DentalProcedure | null> {
    const result = await this.service.getDentalProcedure(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => HealthInsurance, {
    nullable: true,
    name: "healthInsurance",
  })
  async getHealthInsurance(
    @graphql.Parent() parent: DentalProcedurePrice
  ): Promise<HealthInsurance | null> {
    const result = await this.service.getHealthInsurance(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
