/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DentalProcedurePrice as PrismaDentalProcedurePrice,
  DentalProcedure as PrismaDentalProcedure,
  HealthInsurance as PrismaHealthInsurance,
} from "@prisma/client";

export class DentalProcedurePriceServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DentalProcedurePriceCountArgs, "select">
  ): Promise<number> {
    return this.prisma.dentalProcedurePrice.count(args);
  }

  async dentalProcedurePrices(
    args: Prisma.DentalProcedurePriceFindManyArgs
  ): Promise<PrismaDentalProcedurePrice[]> {
    return this.prisma.dentalProcedurePrice.findMany(args);
  }
  async dentalProcedurePrice(
    args: Prisma.DentalProcedurePriceFindUniqueArgs
  ): Promise<PrismaDentalProcedurePrice | null> {
    return this.prisma.dentalProcedurePrice.findUnique(args);
  }
  async createDentalProcedurePrice(
    args: Prisma.DentalProcedurePriceCreateArgs
  ): Promise<PrismaDentalProcedurePrice> {
    return this.prisma.dentalProcedurePrice.create(args);
  }
  async updateDentalProcedurePrice(
    args: Prisma.DentalProcedurePriceUpdateArgs
  ): Promise<PrismaDentalProcedurePrice> {
    return this.prisma.dentalProcedurePrice.update(args);
  }
  async deleteDentalProcedurePrice(
    args: Prisma.DentalProcedurePriceDeleteArgs
  ): Promise<PrismaDentalProcedurePrice> {
    return this.prisma.dentalProcedurePrice.delete(args);
  }

  async getDentalProcedure(
    parentId: number
  ): Promise<PrismaDentalProcedure | null> {
    return this.prisma.dentalProcedurePrice
      .findUnique({
        where: { id: parentId },
      })
      .dentalProcedure();
  }

  async getHealthInsurance(
    parentId: number
  ): Promise<PrismaHealthInsurance | null> {
    return this.prisma.dentalProcedurePrice
      .findUnique({
        where: { id: parentId },
      })
      .healthInsurance();
  }
}
