/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RefreshTokenService } from "../refreshToken.service";
import { RefreshTokenCreateInput } from "./RefreshTokenCreateInput";
import { RefreshToken } from "./RefreshToken";
import { RefreshTokenFindManyArgs } from "./RefreshTokenFindManyArgs";
import { RefreshTokenWhereUniqueInput } from "./RefreshTokenWhereUniqueInput";
import { RefreshTokenUpdateInput } from "./RefreshTokenUpdateInput";

export class RefreshTokenControllerBase {
  constructor(protected readonly service: RefreshTokenService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: RefreshToken })
  async createRefreshToken(
    @common.Body() data: RefreshTokenCreateInput
  ): Promise<RefreshToken> {
    return await this.service.createRefreshToken({
      data: {
        ...data,

        user: {
          connect: data.user,
        },
      },
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        token: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [RefreshToken] })
  @ApiNestedQuery(RefreshTokenFindManyArgs)
  async refreshTokens(@common.Req() request: Request): Promise<RefreshToken[]> {
    const args = plainToClass(RefreshTokenFindManyArgs, request.query);
    return this.service.refreshTokens({
      ...args,
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        token: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: RefreshToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async refreshToken(
    @common.Param() params: RefreshTokenWhereUniqueInput
  ): Promise<RefreshToken | null> {
    const result = await this.service.refreshToken({
      where: params,
      select: {
        createdAt: true,
        expiresAt: true,
        id: true,
        token: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: RefreshToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRefreshToken(
    @common.Param() params: RefreshTokenWhereUniqueInput,
    @common.Body() data: RefreshTokenUpdateInput
  ): Promise<RefreshToken | null> {
    try {
      return await this.service.updateRefreshToken({
        where: params,
        data: {
          ...data,

          user: {
            connect: data.user,
          },
        },
        select: {
          createdAt: true,
          expiresAt: true,
          id: true,
          token: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: RefreshToken })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRefreshToken(
    @common.Param() params: RefreshTokenWhereUniqueInput
  ): Promise<RefreshToken | null> {
    try {
      return await this.service.deleteRefreshToken({
        where: params,
        select: {
          createdAt: true,
          expiresAt: true,
          id: true,
          token: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
