/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { RefreshToken } from "./RefreshToken";
import { RefreshTokenCountArgs } from "./RefreshTokenCountArgs";
import { RefreshTokenFindManyArgs } from "./RefreshTokenFindManyArgs";
import { RefreshTokenFindUniqueArgs } from "./RefreshTokenFindUniqueArgs";
import { CreateRefreshTokenArgs } from "./CreateRefreshTokenArgs";
import { UpdateRefreshTokenArgs } from "./UpdateRefreshTokenArgs";
import { DeleteRefreshTokenArgs } from "./DeleteRefreshTokenArgs";
import { User } from "../../user/base/User";
import { RefreshTokenService } from "../refreshToken.service";
@graphql.Resolver(() => RefreshToken)
export class RefreshTokenResolverBase {
  constructor(protected readonly service: RefreshTokenService) {}

  async _refreshTokensMeta(
    @graphql.Args() args: RefreshTokenCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [RefreshToken])
  async refreshTokens(
    @graphql.Args() args: RefreshTokenFindManyArgs
  ): Promise<RefreshToken[]> {
    return this.service.refreshTokens(args);
  }

  @graphql.Query(() => RefreshToken, { nullable: true })
  async refreshToken(
    @graphql.Args() args: RefreshTokenFindUniqueArgs
  ): Promise<RefreshToken | null> {
    const result = await this.service.refreshToken(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => RefreshToken)
  async createRefreshToken(
    @graphql.Args() args: CreateRefreshTokenArgs
  ): Promise<RefreshToken> {
    return await this.service.createRefreshToken({
      ...args,
      data: {
        ...args.data,

        user: {
          connect: args.data.user,
        },
      },
    });
  }

  @graphql.Mutation(() => RefreshToken)
  async updateRefreshToken(
    @graphql.Args() args: UpdateRefreshTokenArgs
  ): Promise<RefreshToken | null> {
    try {
      return await this.service.updateRefreshToken({
        ...args,
        data: {
          ...args.data,

          user: {
            connect: args.data.user,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => RefreshToken)
  async deleteRefreshToken(
    @graphql.Args() args: DeleteRefreshTokenArgs
  ): Promise<RefreshToken | null> {
    try {
      return await this.service.deleteRefreshToken(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  async getUser(@graphql.Parent() parent: RefreshToken): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
