/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsString,
  MaxLength,
  IsEnum,
} from "class-validator";
import { Type } from "class-transformer";
import { MessageCreateNestedManyWithoutAppointmentsInput } from "./MessageCreateNestedManyWithoutAppointmentsInput";
import { PatientWhereUniqueInput } from "../../patient/base/PatientWhereUniqueInput";
import { ProfessionalWhereUniqueInput } from "../../professional/base/ProfessionalWhereUniqueInput";
import { EnumAppointmentStatus } from "./EnumAppointmentStatus";

@InputType()
class AppointmentCreateInput {
  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  endTime!: Date;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutAppointmentsInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutAppointmentsInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutAppointmentsInput, {
    nullable: true,
  })
  message?: MessageCreateNestedManyWithoutAppointmentsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notes?: string | null;

  @ApiProperty({
    required: true,
    type: () => PatientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PatientWhereUniqueInput)
  @Field(() => PatientWhereUniqueInput)
  patient!: PatientWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: () => ProfessionalWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ProfessionalWhereUniqueInput)
  @Field(() => ProfessionalWhereUniqueInput)
  professional!: ProfessionalWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  reason?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  startTime!: Date;

  @ApiProperty({
    required: true,
    enum: EnumAppointmentStatus,
  })
  @IsEnum(EnumAppointmentStatus)
  @Field(() => EnumAppointmentStatus)
  status!: "SCHEDULED" | "CONFIRMED" | "CANCELLED" | "COMPLETED" | "NO_SHOW";

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { AppointmentCreateInput as AppointmentCreateInput };
