/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { OdontogramService } from "../odontogram.service";
import { OdontogramCreateInput } from "./OdontogramCreateInput";
import { Odontogram } from "./Odontogram";
import { OdontogramFindManyArgs } from "./OdontogramFindManyArgs";
import { OdontogramWhereUniqueInput } from "./OdontogramWhereUniqueInput";
import { OdontogramUpdateInput } from "./OdontogramUpdateInput";
import { OdontogramEntryFindManyArgs } from "../../odontogramEntry/base/OdontogramEntryFindManyArgs";
import { OdontogramEntry } from "../../odontogramEntry/base/OdontogramEntry";
import { OdontogramEntryWhereUniqueInput } from "../../odontogramEntry/base/OdontogramEntryWhereUniqueInput";

export class OdontogramControllerBase {
  constructor(protected readonly service: OdontogramService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Odontogram })
  async createOdontogram(
    @common.Body() data: OdontogramCreateInput
  ): Promise<Odontogram> {
    return await this.service.createOdontogram({
      data: {
        ...data,

        patient: {
          connect: data.patient,
        },
      },
      select: {
        createdAt: true,
        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Odontogram] })
  @ApiNestedQuery(OdontogramFindManyArgs)
  async odontograms(@common.Req() request: Request): Promise<Odontogram[]> {
    const args = plainToClass(OdontogramFindManyArgs, request.query);
    return this.service.odontograms({
      ...args,
      select: {
        createdAt: true,
        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Odontogram })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async odontogram(
    @common.Param() params: OdontogramWhereUniqueInput
  ): Promise<Odontogram | null> {
    const result = await this.service.odontogram({
      where: params,
      select: {
        createdAt: true,
        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Odontogram })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateOdontogram(
    @common.Param() params: OdontogramWhereUniqueInput,
    @common.Body() data: OdontogramUpdateInput
  ): Promise<Odontogram | null> {
    try {
      return await this.service.updateOdontogram({
        where: params,
        data: {
          ...data,

          patient: {
            connect: data.patient,
          },
        },
        select: {
          createdAt: true,
          id: true,

          patient: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Odontogram })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteOdontogram(
    @common.Param() params: OdontogramWhereUniqueInput
  ): Promise<Odontogram | null> {
    try {
      return await this.service.deleteOdontogram({
        where: params,
        select: {
          createdAt: true,
          id: true,

          patient: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/odontogramEntry")
  @ApiNestedQuery(OdontogramEntryFindManyArgs)
  async findOdontogramEntry(
    @common.Req() request: Request,
    @common.Param() params: OdontogramWhereUniqueInput
  ): Promise<OdontogramEntry[]> {
    const query = plainToClass(OdontogramEntryFindManyArgs, request.query);
    const results = await this.service.findOdontogramEntry(params.id, {
      ...query,
      select: {
        color: true,
        conditionType: true,
        createdAt: true,
        id: true,
        notes: true,

        odontogram: {
          select: {
            id: true,
          },
        },

        surface: true,
        tooth: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/odontogramEntry")
  async connectOdontogramEntry(
    @common.Param() params: OdontogramWhereUniqueInput,
    @common.Body() body: OdontogramEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      odontogramEntry: {
        connect: body,
      },
    };
    await this.service.updateOdontogram({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/odontogramEntry")
  async updateOdontogramEntry(
    @common.Param() params: OdontogramWhereUniqueInput,
    @common.Body() body: OdontogramEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      odontogramEntry: {
        set: body,
      },
    };
    await this.service.updateOdontogram({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/odontogramEntry")
  async disconnectOdontogramEntry(
    @common.Param() params: OdontogramWhereUniqueInput,
    @common.Body() body: OdontogramEntryWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      odontogramEntry: {
        disconnect: body,
      },
    };
    await this.service.updateOdontogram({
      where: params,
      data,
      select: { id: true },
    });
  }
}
