/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Odontogram as PrismaOdontogram,
  OdontogramEntry as PrismaOdontogramEntry,
  Patient as PrismaPatient,
} from "@prisma/client";

export class OdontogramServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.OdontogramCountArgs, "select">
  ): Promise<number> {
    return this.prisma.odontogram.count(args);
  }

  async odontograms(
    args: Prisma.OdontogramFindManyArgs
  ): Promise<PrismaOdontogram[]> {
    return this.prisma.odontogram.findMany(args);
  }
  async odontogram(
    args: Prisma.OdontogramFindUniqueArgs
  ): Promise<PrismaOdontogram | null> {
    return this.prisma.odontogram.findUnique(args);
  }
  async createOdontogram(
    args: Prisma.OdontogramCreateArgs
  ): Promise<PrismaOdontogram> {
    return this.prisma.odontogram.create(args);
  }
  async updateOdontogram(
    args: Prisma.OdontogramUpdateArgs
  ): Promise<PrismaOdontogram> {
    return this.prisma.odontogram.update(args);
  }
  async deleteOdontogram(
    args: Prisma.OdontogramDeleteArgs
  ): Promise<PrismaOdontogram> {
    return this.prisma.odontogram.delete(args);
  }

  async findOdontogramEntry(
    parentId: number,
    args: Prisma.OdontogramEntryFindManyArgs
  ): Promise<PrismaOdontogramEntry[]> {
    return this.prisma.odontogram
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .odontogramEntry(args);
  }

  async getPatient(parentId: number): Promise<PrismaPatient | null> {
    return this.prisma.odontogram
      .findUnique({
        where: { id: parentId },
      })
      .patient();
  }
}
