/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Odontogram } from "./Odontogram";
import { OdontogramCountArgs } from "./OdontogramCountArgs";
import { OdontogramFindManyArgs } from "./OdontogramFindManyArgs";
import { OdontogramFindUniqueArgs } from "./OdontogramFindUniqueArgs";
import { CreateOdontogramArgs } from "./CreateOdontogramArgs";
import { UpdateOdontogramArgs } from "./UpdateOdontogramArgs";
import { DeleteOdontogramArgs } from "./DeleteOdontogramArgs";
import { OdontogramEntryFindManyArgs } from "../../odontogramEntry/base/OdontogramEntryFindManyArgs";
import { OdontogramEntry } from "../../odontogramEntry/base/OdontogramEntry";
import { Patient } from "../../patient/base/Patient";
import { OdontogramService } from "../odontogram.service";
@graphql.Resolver(() => Odontogram)
export class OdontogramResolverBase {
  constructor(protected readonly service: OdontogramService) {}

  async _odontogramsMeta(
    @graphql.Args() args: OdontogramCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Odontogram])
  async odontograms(
    @graphql.Args() args: OdontogramFindManyArgs
  ): Promise<Odontogram[]> {
    return this.service.odontograms(args);
  }

  @graphql.Query(() => Odontogram, { nullable: true })
  async odontogram(
    @graphql.Args() args: OdontogramFindUniqueArgs
  ): Promise<Odontogram | null> {
    const result = await this.service.odontogram(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Odontogram)
  async createOdontogram(
    @graphql.Args() args: CreateOdontogramArgs
  ): Promise<Odontogram> {
    return await this.service.createOdontogram({
      ...args,
      data: {
        ...args.data,

        patient: {
          connect: args.data.patient,
        },
      },
    });
  }

  @graphql.Mutation(() => Odontogram)
  async updateOdontogram(
    @graphql.Args() args: UpdateOdontogramArgs
  ): Promise<Odontogram | null> {
    try {
      return await this.service.updateOdontogram({
        ...args,
        data: {
          ...args.data,

          patient: {
            connect: args.data.patient,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Odontogram)
  async deleteOdontogram(
    @graphql.Args() args: DeleteOdontogramArgs
  ): Promise<Odontogram | null> {
    try {
      return await this.service.deleteOdontogram(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [OdontogramEntry], { name: "odontogramEntry" })
  async findOdontogramEntry(
    @graphql.Parent() parent: Odontogram,
    @graphql.Args() args: OdontogramEntryFindManyArgs
  ): Promise<OdontogramEntry[]> {
    const results = await this.service.findOdontogramEntry(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Patient, {
    nullable: true,
    name: "patient",
  })
  async getPatient(
    @graphql.Parent() parent: Odontogram
  ): Promise<Patient | null> {
    const result = await this.service.getPatient(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
