/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AppointmentWhereUniqueInput } from "../../appointment/base/AppointmentWhereUniqueInput";
import {
  ValidateNested,
  IsOptional,
  IsEnum,
  IsString,
  MaxLength,
  IsDate,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumMessageChannel } from "./EnumMessageChannel";
import { PatientWhereUniqueInput } from "../../patient/base/PatientWhereUniqueInput";
import { EnumMessageStatus } from "./EnumMessageStatus";

@InputType()
class MessageCreateInput {
  @ApiProperty({
    required: false,
    type: () => AppointmentWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => AppointmentWhereUniqueInput)
  @IsOptional()
  @Field(() => AppointmentWhereUniqueInput, {
    nullable: true,
  })
  appointment?: AppointmentWhereUniqueInput | null;

  @ApiProperty({
    required: true,
    enum: EnumMessageChannel,
  })
  @IsEnum(EnumMessageChannel)
  @Field(() => EnumMessageChannel)
  channel!: "WHATSAPP" | "EMAIL" | "SMS";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  content!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  errorField?: string | null;

  @ApiProperty({
    required: false,
    type: () => PatientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PatientWhereUniqueInput)
  @IsOptional()
  @Field(() => PatientWhereUniqueInput, {
    nullable: true,
  })
  patient?: PatientWhereUniqueInput | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  sentAt?: Date | null;

  @ApiProperty({
    required: true,
    enum: EnumMessageStatus,
  })
  @IsEnum(EnumMessageStatus)
  @Field(() => EnumMessageStatus)
  status!: "PENDING" | "SENT" | "FAILED";
}

export { MessageCreateInput as MessageCreateInput };
