/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Appointment } from "../../appointment/base/Appointment";
import {
  ValidateNested,
  IsOptional,
  IsEnum,
  IsString,
  MaxLength,
  IsDate,
  IsInt,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumMessageChannel } from "./EnumMessageChannel";
import { Patient } from "../../patient/base/Patient";
import { EnumMessageStatus } from "./EnumMessageStatus";

@ObjectType()
class Message {
  @ApiProperty({
    required: false,
    type: () => Appointment,
  })
  @ValidateNested()
  @Type(() => Appointment)
  @IsOptional()
  appointment?: Appointment | null;

  @ApiProperty({
    required: true,
    enum: EnumMessageChannel,
  })
  @IsEnum(EnumMessageChannel)
  @Field(() => EnumMessageChannel, {
    nullable: true,
  })
  channel?: "WHATSAPP" | "EMAIL" | "SMS";

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  content!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  errorField!: string | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: () => Patient,
  })
  @ValidateNested()
  @Type(() => Patient)
  @IsOptional()
  patient?: Patient | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  sentAt!: Date | null;

  @ApiProperty({
    required: true,
    enum: EnumMessageStatus,
  })
  @IsEnum(EnumMessageStatus)
  @Field(() => EnumMessageStatus, {
    nullable: true,
  })
  status?: "PENDING" | "SENT" | "FAILED";
}

export { Message as Message };
