/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  Patient as PrismaPatient,
  Appointment as PrismaAppointment,
  Invoice as PrismaInvoice,
  Message as PrismaMessage,
  Clinic as PrismaClinic,
  MedicalRecord as PrismaMedicalRecord,
  Odontogram as PrismaOdontogram,
} from "@prisma/client";

export class PatientServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.PatientCountArgs, "select">): Promise<number> {
    return this.prisma.patient.count(args);
  }

  async patients(args: Prisma.PatientFindManyArgs): Promise<PrismaPatient[]> {
    return this.prisma.patient.findMany(args);
  }
  async patient(
    args: Prisma.PatientFindUniqueArgs
  ): Promise<PrismaPatient | null> {
    return this.prisma.patient.findUnique(args);
  }
  async createPatient(args: Prisma.PatientCreateArgs): Promise<PrismaPatient> {
    return this.prisma.patient.create(args);
  }
  async updatePatient(args: Prisma.PatientUpdateArgs): Promise<PrismaPatient> {
    return this.prisma.patient.update(args);
  }
  async deletePatient(args: Prisma.PatientDeleteArgs): Promise<PrismaPatient> {
    return this.prisma.patient.delete(args);
  }

  async findAppointment(
    parentId: number,
    args: Prisma.AppointmentFindManyArgs
  ): Promise<PrismaAppointment[]> {
    return this.prisma.patient
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .appointment(args);
  }

  async findInvoice(
    parentId: number,
    args: Prisma.InvoiceFindManyArgs
  ): Promise<PrismaInvoice[]> {
    return this.prisma.patient
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .invoice(args);
  }

  async findMessage(
    parentId: number,
    args: Prisma.MessageFindManyArgs
  ): Promise<PrismaMessage[]> {
    return this.prisma.patient
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .message(args);
  }

  async getClinic(parentId: number): Promise<PrismaClinic | null> {
    return this.prisma.patient
      .findUnique({
        where: { id: parentId },
      })
      .clinic();
  }

  async getMedicalRecord(
    parentId: number
  ): Promise<PrismaMedicalRecord | null> {
    return this.prisma.patient
      .findUnique({
        where: { id: parentId },
      })
      .medicalRecord();
  }

  async getOdontogram(parentId: number): Promise<PrismaOdontogram | null> {
    return this.prisma.patient
      .findUnique({
        where: { id: parentId },
      })
      .odontogram();
  }
}
