/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { AppointmentUpdateManyWithoutPatientsInput } from "./AppointmentUpdateManyWithoutPatientsInput";
import { Type } from "class-transformer";
import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";
import { InvoiceUpdateManyWithoutPatientsInput } from "./InvoiceUpdateManyWithoutPatientsInput";
import { MedicalRecordWhereUniqueInput } from "../../medicalRecord/base/MedicalRecordWhereUniqueInput";
import { MessageUpdateManyWithoutPatientsInput } from "./MessageUpdateManyWithoutPatientsInput";
import { OdontogramWhereUniqueInput } from "../../odontogram/base/OdontogramWhereUniqueInput";

@InputType()
class PatientUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentUpdateManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentUpdateManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => AppointmentUpdateManyWithoutPatientsInput, {
    nullable: true,
  })
  appointment?: AppointmentUpdateManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  birthDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  dni?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  gender?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceUpdateManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => InvoiceUpdateManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => InvoiceUpdateManyWithoutPatientsInput, {
    nullable: true,
  })
  invoice?: InvoiceUpdateManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string;

  @ApiProperty({
    required: false,
    type: () => MedicalRecordWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MedicalRecordWhereUniqueInput)
  @IsOptional()
  @Field(() => MedicalRecordWhereUniqueInput, {
    nullable: true,
  })
  medicalRecord?: MedicalRecordWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => MessageUpdateManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => MessageUpdateManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => MessageUpdateManyWithoutPatientsInput, {
    nullable: true,
  })
  message?: MessageUpdateManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
    type: () => OdontogramWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OdontogramWhereUniqueInput)
  @IsOptional()
  @Field(() => OdontogramWhereUniqueInput, {
    nullable: true,
  })
  odontogram?: OdontogramWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date;
}

export { PatientUpdateInput as PatientUpdateInput };
