/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Patient } from "./Patient";
import { PatientCountArgs } from "./PatientCountArgs";
import { PatientFindManyArgs } from "./PatientFindManyArgs";
import { PatientFindUniqueArgs } from "./PatientFindUniqueArgs";
import { CreatePatientArgs } from "./CreatePatientArgs";
import { UpdatePatientArgs } from "./UpdatePatientArgs";
import { DeletePatientArgs } from "./DeletePatientArgs";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { InvoiceFindManyArgs } from "../../invoice/base/InvoiceFindManyArgs";
import { Invoice } from "../../invoice/base/Invoice";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { Clinic } from "../../clinic/base/Clinic";
import { MedicalRecord } from "../../medicalRecord/base/MedicalRecord";
import { Odontogram } from "../../odontogram/base/Odontogram";
import { PatientService } from "../patient.service";
@graphql.Resolver(() => Patient)
export class PatientResolverBase {
  constructor(protected readonly service: PatientService) {}

  async _patientsMeta(
    @graphql.Args() args: PatientCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Patient])
  async patients(
    @graphql.Args() args: PatientFindManyArgs
  ): Promise<Patient[]> {
    return this.service.patients(args);
  }

  @graphql.Query(() => Patient, { nullable: true })
  async patient(
    @graphql.Args() args: PatientFindUniqueArgs
  ): Promise<Patient | null> {
    const result = await this.service.patient(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Patient)
  async createPatient(
    @graphql.Args() args: CreatePatientArgs
  ): Promise<Patient> {
    return await this.service.createPatient({
      ...args,
      data: {
        ...args.data,

        clinic: args.data.clinic
          ? {
              connect: args.data.clinic,
            }
          : undefined,

        medicalRecord: args.data.medicalRecord
          ? {
              connect: args.data.medicalRecord,
            }
          : undefined,

        odontogram: args.data.odontogram
          ? {
              connect: args.data.odontogram,
            }
          : undefined,
      },
    });
  }

  @graphql.Mutation(() => Patient)
  async updatePatient(
    @graphql.Args() args: UpdatePatientArgs
  ): Promise<Patient | null> {
    try {
      return await this.service.updatePatient({
        ...args,
        data: {
          ...args.data,

          clinic: args.data.clinic
            ? {
                connect: args.data.clinic,
              }
            : undefined,

          medicalRecord: args.data.medicalRecord
            ? {
                connect: args.data.medicalRecord,
              }
            : undefined,

          odontogram: args.data.odontogram
            ? {
                connect: args.data.odontogram,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Patient)
  async deletePatient(
    @graphql.Args() args: DeletePatientArgs
  ): Promise<Patient | null> {
    try {
      return await this.service.deletePatient(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [Appointment], { name: "appointment" })
  async findAppointment(
    @graphql.Parent() parent: Patient,
    @graphql.Args() args: AppointmentFindManyArgs
  ): Promise<Appointment[]> {
    const results = await this.service.findAppointment(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Invoice], { name: "invoice" })
  async findInvoice(
    @graphql.Parent() parent: Patient,
    @graphql.Args() args: InvoiceFindManyArgs
  ): Promise<Invoice[]> {
    const results = await this.service.findInvoice(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [Message], { name: "message" })
  async findMessage(
    @graphql.Parent() parent: Patient,
    @graphql.Args() args: MessageFindManyArgs
  ): Promise<Message[]> {
    const results = await this.service.findMessage(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Clinic, {
    nullable: true,
    name: "clinic",
  })
  async getClinic(@graphql.Parent() parent: Patient): Promise<Clinic | null> {
    const result = await this.service.getClinic(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => MedicalRecord, {
    nullable: true,
    name: "medicalRecord",
  })
  async getMedicalRecord(
    @graphql.Parent() parent: Patient
  ): Promise<MedicalRecord | null> {
    const result = await this.service.getMedicalRecord(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @graphql.ResolveField(() => Odontogram, {
    nullable: true,
    name: "odontogram",
  })
  async getOdontogram(
    @graphql.Parent() parent: Patient
  ): Promise<Odontogram | null> {
    const result = await this.service.getOdontogram(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
