/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  ValidateNested,
  IsDate,
} from "class-validator";
import { AppointmentCreateNestedManyWithoutPatientsInput } from "./AppointmentCreateNestedManyWithoutPatientsInput";
import { Type } from "class-transformer";
import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";
import { InvoiceCreateNestedManyWithoutPatientsInput } from "./InvoiceCreateNestedManyWithoutPatientsInput";
import { MedicalRecordWhereUniqueInput } from "../../medicalRecord/base/MedicalRecordWhereUniqueInput";
import { MessageCreateNestedManyWithoutPatientsInput } from "./MessageCreateNestedManyWithoutPatientsInput";
import { OdontogramWhereUniqueInput } from "../../odontogram/base/OdontogramWhereUniqueInput";

@InputType()
class PatientCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  address?: string | null;

  @ApiProperty({
    required: false,
    type: () => AppointmentCreateNestedManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => AppointmentCreateNestedManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => AppointmentCreateNestedManyWithoutPatientsInput, {
    nullable: true,
  })
  appointment?: AppointmentCreateNestedManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  birthDate?: Date | null;

  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  dni?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  email?: string | null;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  firstName!: string;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  gender?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceCreateNestedManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => InvoiceCreateNestedManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => InvoiceCreateNestedManyWithoutPatientsInput, {
    nullable: true,
  })
  invoice?: InvoiceCreateNestedManyWithoutPatientsInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  lastName!: string;

  @ApiProperty({
    required: false,
    type: () => MedicalRecordWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => MedicalRecordWhereUniqueInput)
  @IsOptional()
  @Field(() => MedicalRecordWhereUniqueInput, {
    nullable: true,
  })
  medicalRecord?: MedicalRecordWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => MessageCreateNestedManyWithoutPatientsInput,
  })
  @ValidateNested()
  @Type(() => MessageCreateNestedManyWithoutPatientsInput)
  @IsOptional()
  @Field(() => MessageCreateNestedManyWithoutPatientsInput, {
    nullable: true,
  })
  message?: MessageCreateNestedManyWithoutPatientsInput;

  @ApiProperty({
    required: false,
    type: () => OdontogramWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => OdontogramWhereUniqueInput)
  @IsOptional()
  @Field(() => OdontogramWhereUniqueInput, {
    nullable: true,
  })
  odontogram?: OdontogramWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  phone?: string | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { PatientCreateInput as PatientCreateInput };
