/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { PatientService } from "../patient.service";
import { PatientCreateInput } from "./PatientCreateInput";
import { Patient } from "./Patient";
import { PatientFindManyArgs } from "./PatientFindManyArgs";
import { PatientWhereUniqueInput } from "./PatientWhereUniqueInput";
import { PatientUpdateInput } from "./PatientUpdateInput";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { AppointmentWhereUniqueInput } from "../../appointment/base/AppointmentWhereUniqueInput";
import { InvoiceFindManyArgs } from "../../invoice/base/InvoiceFindManyArgs";
import { Invoice } from "../../invoice/base/Invoice";
import { InvoiceWhereUniqueInput } from "../../invoice/base/InvoiceWhereUniqueInput";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { MessageWhereUniqueInput } from "../../message/base/MessageWhereUniqueInput";

export class PatientControllerBase {
  constructor(protected readonly service: PatientService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Patient })
  async createPatient(
    @common.Body() data: PatientCreateInput
  ): Promise<Patient> {
    return await this.service.createPatient({
      data: {
        ...data,

        clinic: data.clinic
          ? {
              connect: data.clinic,
            }
          : undefined,

        medicalRecord: data.medicalRecord
          ? {
              connect: data.medicalRecord,
            }
          : undefined,

        odontogram: data.odontogram
          ? {
              connect: data.odontogram,
            }
          : undefined,
      },
      select: {
        address: true,
        birthDate: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dni: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,

        medicalRecord: {
          select: {
            id: true,
          },
        },

        odontogram: {
          select: {
            id: true,
          },
        },

        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Patient] })
  @ApiNestedQuery(PatientFindManyArgs)
  async patients(@common.Req() request: Request): Promise<Patient[]> {
    const args = plainToClass(PatientFindManyArgs, request.query);
    return this.service.patients({
      ...args,
      select: {
        address: true,
        birthDate: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dni: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,

        medicalRecord: {
          select: {
            id: true,
          },
        },

        odontogram: {
          select: {
            id: true,
          },
        },

        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Patient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async patient(
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<Patient | null> {
    const result = await this.service.patient({
      where: params,
      select: {
        address: true,
        birthDate: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        dni: true,
        email: true,
        firstName: true,
        gender: true,
        id: true,
        lastName: true,

        medicalRecord: {
          select: {
            id: true,
          },
        },

        odontogram: {
          select: {
            id: true,
          },
        },

        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Patient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updatePatient(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() data: PatientUpdateInput
  ): Promise<Patient | null> {
    try {
      return await this.service.updatePatient({
        where: params,
        data: {
          ...data,

          clinic: data.clinic
            ? {
                connect: data.clinic,
              }
            : undefined,

          medicalRecord: data.medicalRecord
            ? {
                connect: data.medicalRecord,
              }
            : undefined,

          odontogram: data.odontogram
            ? {
                connect: data.odontogram,
              }
            : undefined,
        },
        select: {
          address: true,
          birthDate: true,

          clinic: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dni: true,
          email: true,
          firstName: true,
          gender: true,
          id: true,
          lastName: true,

          medicalRecord: {
            select: {
              id: true,
            },
          },

          odontogram: {
            select: {
              id: true,
            },
          },

          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Patient })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deletePatient(
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<Patient | null> {
    try {
      return await this.service.deletePatient({
        where: params,
        select: {
          address: true,
          birthDate: true,

          clinic: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          dni: true,
          email: true,
          firstName: true,
          gender: true,
          id: true,
          lastName: true,

          medicalRecord: {
            select: {
              id: true,
            },
          },

          odontogram: {
            select: {
              id: true,
            },
          },

          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/appointment")
  @ApiNestedQuery(AppointmentFindManyArgs)
  async findAppointment(
    @common.Req() request: Request,
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<Appointment[]> {
    const query = plainToClass(AppointmentFindManyArgs, request.query);
    const results = await this.service.findAppointment(params.id, {
      ...query,
      select: {
        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endTime: true,
        id: true,
        notes: true,

        patient: {
          select: {
            id: true,
          },
        },

        professional: {
          select: {
            id: true,
          },
        },

        reason: true,
        startTime: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appointment")
  async connectAppointment(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        connect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appointment")
  async updateAppointment(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        set: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appointment")
  async disconnectAppointment(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        disconnect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/invoice")
  @ApiNestedQuery(InvoiceFindManyArgs)
  async findInvoice(
    @common.Req() request: Request,
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<Invoice[]> {
    const query = plainToClass(InvoiceFindManyArgs, request.query);
    const results = await this.service.findInvoice(params.id, {
      ...query,
      select: {
        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        date: true,
        id: true,
        notes: true,

        patient: {
          select: {
            id: true,
          },
        },

        status: true,
        totalAmount: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/invoice")
  async connectInvoice(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoice: {
        connect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/invoice")
  async updateInvoice(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoice: {
        set: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/invoice")
  async disconnectInvoice(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: InvoiceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoice: {
        disconnect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/message")
  @ApiNestedQuery(MessageFindManyArgs)
  async findMessage(
    @common.Req() request: Request,
    @common.Param() params: PatientWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessage(params.id, {
      ...query,
      select: {
        appointment: {
          select: {
            id: true,
          },
        },

        channel: true,
        content: true,
        createdAt: true,
        errorField: true,
        id: true,

        patient: {
          select: {
            id: true,
          },
        },

        sentAt: true,
        status: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/message")
  async connectMessage(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      message: {
        connect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/message")
  async updateMessage(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      message: {
        set: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/message")
  async disconnectMessage(
    @common.Param() params: PatientWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      message: {
        disconnect: body,
      },
    };
    await this.service.updatePatient({
      where: params,
      data,
      select: { id: true },
    });
  }
}
