/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
  IsNumber,
  Max,
  IsDate,
} from "class-validator";

import { Type } from "class-transformer";
import { InvoiceItemUpdateManyWithoutInvoicesInput } from "./InvoiceItemUpdateManyWithoutInvoicesInput";
import { PatientWhereUniqueInput } from "../../patient/base/PatientWhereUniqueInput";
import { PaymentUpdateManyWithoutInvoicesInput } from "./PaymentUpdateManyWithoutInvoicesInput";
import { EnumInvoiceStatus } from "./EnumInvoiceStatus";

@InputType()
class InvoiceUpdateInput {
  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceItemUpdateManyWithoutInvoicesInput,
  })
  @ValidateNested()
  @Type(() => InvoiceItemUpdateManyWithoutInvoicesInput)
  @IsOptional()
  @Field(() => InvoiceItemUpdateManyWithoutInvoicesInput, {
    nullable: true,
  })
  invoiceItem?: InvoiceItemUpdateManyWithoutInvoicesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notes?: string | null;

  @ApiProperty({
    required: false,
    type: () => PatientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PatientWhereUniqueInput)
  @IsOptional()
  @Field(() => PatientWhereUniqueInput, {
    nullable: true,
  })
  patient?: PatientWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => PaymentUpdateManyWithoutInvoicesInput,
  })
  @ValidateNested()
  @Type(() => PaymentUpdateManyWithoutInvoicesInput)
  @IsOptional()
  @Field(() => PaymentUpdateManyWithoutInvoicesInput, {
    nullable: true,
  })
  payment?: PaymentUpdateManyWithoutInvoicesInput;

  @ApiProperty({
    required: false,
    enum: EnumInvoiceStatus,
  })
  @IsEnum(EnumInvoiceStatus)
  @IsOptional()
  @Field(() => EnumInvoiceStatus, {
    nullable: true,
  })
  status?: "PENDING" | "PAID" | "CANCELLED";

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  totalAmount?: number;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date;
}

export { InvoiceUpdateInput as InvoiceUpdateInput };
