/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Clinic } from "../../clinic/base/Clinic";

import {
  ValidateNested,
  IsOptional,
  IsDate,
  IsInt,
  IsString,
  MaxLength,
  IsEnum,
  IsNumber,
  Max,
} from "class-validator";

import { Type } from "class-transformer";
import { InvoiceItem } from "../../invoiceItem/base/InvoiceItem";
import { Patient } from "../../patient/base/Patient";
import { Payment } from "../../payment/base/Payment";
import { EnumInvoiceStatus } from "./EnumInvoiceStatus";

@ObjectType()
class Invoice {
  @ApiProperty({
    required: false,
    type: () => Clinic,
  })
  @ValidateNested()
  @Type(() => Clinic)
  @IsOptional()
  clinic?: Clinic | null;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  date!: Date;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: () => [InvoiceItem],
  })
  @ValidateNested()
  @Type(() => InvoiceItem)
  @IsOptional()
  invoiceItem?: Array<InvoiceItem>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notes!: string | null;

  @ApiProperty({
    required: true,
    type: () => Patient,
  })
  @ValidateNested()
  @Type(() => Patient)
  patient?: Patient;

  @ApiProperty({
    required: false,
    type: () => [Payment],
  })
  @ValidateNested()
  @Type(() => Payment)
  @IsOptional()
  payment?: Array<Payment>;

  @ApiProperty({
    required: true,
    enum: EnumInvoiceStatus,
  })
  @IsEnum(EnumInvoiceStatus)
  @Field(() => EnumInvoiceStatus, {
    nullable: true,
  })
  status?: "PENDING" | "PAID" | "CANCELLED";

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  totalAmount!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { Invoice as Invoice };
