/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";

import {
  ValidateNested,
  IsOptional,
  IsString,
  MaxLength,
  IsEnum,
  IsNumber,
  Max,
  IsDate,
} from "class-validator";

import { Type } from "class-transformer";
import { InvoiceItemCreateNestedManyWithoutInvoicesInput } from "./InvoiceItemCreateNestedManyWithoutInvoicesInput";
import { PatientWhereUniqueInput } from "../../patient/base/PatientWhereUniqueInput";
import { PaymentCreateNestedManyWithoutInvoicesInput } from "./PaymentCreateNestedManyWithoutInvoicesInput";
import { EnumInvoiceStatus } from "./EnumInvoiceStatus";

@InputType()
class InvoiceCreateInput {
  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceItemCreateNestedManyWithoutInvoicesInput,
  })
  @ValidateNested()
  @Type(() => InvoiceItemCreateNestedManyWithoutInvoicesInput)
  @IsOptional()
  @Field(() => InvoiceItemCreateNestedManyWithoutInvoicesInput, {
    nullable: true,
  })
  invoiceItem?: InvoiceItemCreateNestedManyWithoutInvoicesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  notes?: string | null;

  @ApiProperty({
    required: true,
    type: () => PatientWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => PatientWhereUniqueInput)
  @Field(() => PatientWhereUniqueInput)
  patient!: PatientWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => PaymentCreateNestedManyWithoutInvoicesInput,
  })
  @ValidateNested()
  @Type(() => PaymentCreateNestedManyWithoutInvoicesInput)
  @IsOptional()
  @Field(() => PaymentCreateNestedManyWithoutInvoicesInput, {
    nullable: true,
  })
  payment?: PaymentCreateNestedManyWithoutInvoicesInput;

  @ApiProperty({
    required: true,
    enum: EnumInvoiceStatus,
  })
  @IsEnum(EnumInvoiceStatus)
  @Field(() => EnumInvoiceStatus)
  status!: "PENDING" | "PAID" | "CANCELLED";

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  totalAmount!: number;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { InvoiceCreateInput as InvoiceCreateInput };
