/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { HealthInsuranceService } from "../healthInsurance.service";
import { HealthInsuranceCreateInput } from "./HealthInsuranceCreateInput";
import { HealthInsurance } from "./HealthInsurance";
import { HealthInsuranceFindManyArgs } from "./HealthInsuranceFindManyArgs";
import { HealthInsuranceWhereUniqueInput } from "./HealthInsuranceWhereUniqueInput";
import { HealthInsuranceUpdateInput } from "./HealthInsuranceUpdateInput";
import { DentalProcedurePriceFindManyArgs } from "../../dentalProcedurePrice/base/DentalProcedurePriceFindManyArgs";
import { DentalProcedurePrice } from "../../dentalProcedurePrice/base/DentalProcedurePrice";
import { DentalProcedurePriceWhereUniqueInput } from "../../dentalProcedurePrice/base/DentalProcedurePriceWhereUniqueInput";

export class HealthInsuranceControllerBase {
  constructor(protected readonly service: HealthInsuranceService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HealthInsurance })
  async createHealthInsurance(
    @common.Body() data: HealthInsuranceCreateInput
  ): Promise<HealthInsurance> {
    return await this.service.createHealthInsurance({
      data: data,
      select: {
        code: true,
        contact: true,
        createdAt: true,
        id: true,
        name: true,
        observations: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [HealthInsurance] })
  @ApiNestedQuery(HealthInsuranceFindManyArgs)
  async healthInsurances(
    @common.Req() request: Request
  ): Promise<HealthInsurance[]> {
    const args = plainToClass(HealthInsuranceFindManyArgs, request.query);
    return this.service.healthInsurances({
      ...args,
      select: {
        code: true,
        contact: true,
        createdAt: true,
        id: true,
        name: true,
        observations: true,
        phone: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HealthInsurance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async healthInsurance(
    @common.Param() params: HealthInsuranceWhereUniqueInput
  ): Promise<HealthInsurance | null> {
    const result = await this.service.healthInsurance({
      where: params,
      select: {
        code: true,
        contact: true,
        createdAt: true,
        id: true,
        name: true,
        observations: true,
        phone: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HealthInsurance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateHealthInsurance(
    @common.Param() params: HealthInsuranceWhereUniqueInput,
    @common.Body() data: HealthInsuranceUpdateInput
  ): Promise<HealthInsurance | null> {
    try {
      return await this.service.updateHealthInsurance({
        where: params,
        data: data,
        select: {
          code: true,
          contact: true,
          createdAt: true,
          id: true,
          name: true,
          observations: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HealthInsurance })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteHealthInsurance(
    @common.Param() params: HealthInsuranceWhereUniqueInput
  ): Promise<HealthInsurance | null> {
    try {
      return await this.service.deleteHealthInsurance({
        where: params,
        select: {
          code: true,
          contact: true,
          createdAt: true,
          id: true,
          name: true,
          observations: true,
          phone: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/dentalProcedurePrice")
  @ApiNestedQuery(DentalProcedurePriceFindManyArgs)
  async findDentalProcedurePrice(
    @common.Req() request: Request,
    @common.Param() params: HealthInsuranceWhereUniqueInput
  ): Promise<DentalProcedurePrice[]> {
    const query = plainToClass(DentalProcedurePriceFindManyArgs, request.query);
    const results = await this.service.findDentalProcedurePrice(params.id, {
      ...query,
      select: {
        createdAt: true,

        dentalProcedure: {
          select: {
            id: true,
          },
        },

        healthInsurance: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dentalProcedurePrice")
  async connectDentalProcedurePrice(
    @common.Param() params: HealthInsuranceWhereUniqueInput,
    @common.Body() body: DentalProcedurePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedurePrice: {
        connect: body,
      },
    };
    await this.service.updateHealthInsurance({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dentalProcedurePrice")
  async updateDentalProcedurePrice(
    @common.Param() params: HealthInsuranceWhereUniqueInput,
    @common.Body() body: DentalProcedurePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedurePrice: {
        set: body,
      },
    };
    await this.service.updateHealthInsurance({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dentalProcedurePrice")
  async disconnectDentalProcedurePrice(
    @common.Param() params: HealthInsuranceWhereUniqueInput,
    @common.Body() body: DentalProcedurePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedurePrice: {
        disconnect: body,
      },
    };
    await this.service.updateHealthInsurance({
      where: params,
      data,
      select: { id: true },
    });
  }
}
