/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { HealthInsurance } from "./HealthInsurance";
import { HealthInsuranceCountArgs } from "./HealthInsuranceCountArgs";
import { HealthInsuranceFindManyArgs } from "./HealthInsuranceFindManyArgs";
import { HealthInsuranceFindUniqueArgs } from "./HealthInsuranceFindUniqueArgs";
import { CreateHealthInsuranceArgs } from "./CreateHealthInsuranceArgs";
import { UpdateHealthInsuranceArgs } from "./UpdateHealthInsuranceArgs";
import { DeleteHealthInsuranceArgs } from "./DeleteHealthInsuranceArgs";
import { DentalProcedurePriceFindManyArgs } from "../../dentalProcedurePrice/base/DentalProcedurePriceFindManyArgs";
import { DentalProcedurePrice } from "../../dentalProcedurePrice/base/DentalProcedurePrice";
import { HealthInsuranceService } from "../healthInsurance.service";
@graphql.Resolver(() => HealthInsurance)
export class HealthInsuranceResolverBase {
  constructor(protected readonly service: HealthInsuranceService) {}

  async _healthInsurancesMeta(
    @graphql.Args() args: HealthInsuranceCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [HealthInsurance])
  async healthInsurances(
    @graphql.Args() args: HealthInsuranceFindManyArgs
  ): Promise<HealthInsurance[]> {
    return this.service.healthInsurances(args);
  }

  @graphql.Query(() => HealthInsurance, { nullable: true })
  async healthInsurance(
    @graphql.Args() args: HealthInsuranceFindUniqueArgs
  ): Promise<HealthInsurance | null> {
    const result = await this.service.healthInsurance(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => HealthInsurance)
  async createHealthInsurance(
    @graphql.Args() args: CreateHealthInsuranceArgs
  ): Promise<HealthInsurance> {
    return await this.service.createHealthInsurance({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => HealthInsurance)
  async updateHealthInsurance(
    @graphql.Args() args: UpdateHealthInsuranceArgs
  ): Promise<HealthInsurance | null> {
    try {
      return await this.service.updateHealthInsurance({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => HealthInsurance)
  async deleteHealthInsurance(
    @graphql.Args() args: DeleteHealthInsuranceArgs
  ): Promise<HealthInsurance | null> {
    try {
      return await this.service.deleteHealthInsurance(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DentalProcedurePrice], {
    name: "dentalProcedurePrice",
  })
  async findDentalProcedurePrice(
    @graphql.Parent() parent: HealthInsurance,
    @graphql.Args() args: DentalProcedurePriceFindManyArgs
  ): Promise<DentalProcedurePrice[]> {
    const results = await this.service.findDentalProcedurePrice(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }
}
