/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { ProfessionalService } from "../professional.service";
import { ProfessionalCreateInput } from "./ProfessionalCreateInput";
import { Professional } from "./Professional";
import { ProfessionalFindManyArgs } from "./ProfessionalFindManyArgs";
import { ProfessionalWhereUniqueInput } from "./ProfessionalWhereUniqueInput";
import { ProfessionalUpdateInput } from "./ProfessionalUpdateInput";
import { AppointmentFindManyArgs } from "../../appointment/base/AppointmentFindManyArgs";
import { Appointment } from "../../appointment/base/Appointment";
import { AppointmentWhereUniqueInput } from "../../appointment/base/AppointmentWhereUniqueInput";

export class ProfessionalControllerBase {
  constructor(protected readonly service: ProfessionalService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Professional })
  async createProfessional(
    @common.Body() data: ProfessionalCreateInput
  ): Promise<Professional> {
    return await this.service.createProfessional({
      data: {
        ...data,

        clinic: data.clinic
          ? {
              connect: data.clinic,
            }
          : undefined,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        active: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        license: true,
        phone: true,
        speciality: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Professional] })
  @ApiNestedQuery(ProfessionalFindManyArgs)
  async professionals(@common.Req() request: Request): Promise<Professional[]> {
    const args = plainToClass(ProfessionalFindManyArgs, request.query);
    return this.service.professionals({
      ...args,
      select: {
        active: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        license: true,
        phone: true,
        speciality: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async professional(
    @common.Param() params: ProfessionalWhereUniqueInput
  ): Promise<Professional | null> {
    const result = await this.service.professional({
      where: params,
      select: {
        active: true,

        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        email: true,
        fullName: true,
        id: true,
        license: true,
        phone: true,
        speciality: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateProfessional(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() data: ProfessionalUpdateInput
  ): Promise<Professional | null> {
    try {
      return await this.service.updateProfessional({
        where: params,
        data: {
          ...data,

          clinic: data.clinic
            ? {
                connect: data.clinic,
              }
            : undefined,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          active: true,

          clinic: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          fullName: true,
          id: true,
          license: true,
          phone: true,
          speciality: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Professional })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteProfessional(
    @common.Param() params: ProfessionalWhereUniqueInput
  ): Promise<Professional | null> {
    try {
      return await this.service.deleteProfessional({
        where: params,
        select: {
          active: true,

          clinic: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          email: true,
          fullName: true,
          id: true,
          license: true,
          phone: true,
          speciality: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/appointment")
  @ApiNestedQuery(AppointmentFindManyArgs)
  async findAppointment(
    @common.Req() request: Request,
    @common.Param() params: ProfessionalWhereUniqueInput
  ): Promise<Appointment[]> {
    const query = plainToClass(AppointmentFindManyArgs, request.query);
    const results = await this.service.findAppointment(params.id, {
      ...query,
      select: {
        clinic: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        endTime: true,
        id: true,
        notes: true,

        patient: {
          select: {
            id: true,
          },
        },

        professional: {
          select: {
            id: true,
          },
        },

        reason: true,
        startTime: true,
        status: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/appointment")
  async connectAppointment(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        connect: body,
      },
    };
    await this.service.updateProfessional({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/appointment")
  async updateAppointment(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        set: body,
      },
    };
    await this.service.updateProfessional({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/appointment")
  async disconnectAppointment(
    @common.Param() params: ProfessionalWhereUniqueInput,
    @common.Body() body: AppointmentWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      appointment: {
        disconnect: body,
      },
    };
    await this.service.updateProfessional({
      where: params,
      data,
      select: { id: true },
    });
  }
}
