/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DentalProcedureService } from "../dentalProcedure.service";
import { DentalProcedureCreateInput } from "./DentalProcedureCreateInput";
import { DentalProcedure } from "./DentalProcedure";
import { DentalProcedureFindManyArgs } from "./DentalProcedureFindManyArgs";
import { DentalProcedureWhereUniqueInput } from "./DentalProcedureWhereUniqueInput";
import { DentalProcedureUpdateInput } from "./DentalProcedureUpdateInput";
import { DentalProcedurePriceFindManyArgs } from "../../dentalProcedurePrice/base/DentalProcedurePriceFindManyArgs";
import { DentalProcedurePrice } from "../../dentalProcedurePrice/base/DentalProcedurePrice";
import { DentalProcedurePriceWhereUniqueInput } from "../../dentalProcedurePrice/base/DentalProcedurePriceWhereUniqueInput";
import { InvoiceItemFindManyArgs } from "../../invoiceItem/base/InvoiceItemFindManyArgs";
import { InvoiceItem } from "../../invoiceItem/base/InvoiceItem";
import { InvoiceItemWhereUniqueInput } from "../../invoiceItem/base/InvoiceItemWhereUniqueInput";

export class DentalProcedureControllerBase {
  constructor(protected readonly service: DentalProcedureService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: DentalProcedure })
  async createDentalProcedure(
    @common.Body() data: DentalProcedureCreateInput
  ): Promise<DentalProcedure> {
    return await this.service.createDentalProcedure({
      data: {
        ...data,

        clinic: {
          connect: data.clinic,
        },
      },
      select: {
        active: true,
        basePrice: true,

        clinic: {
          select: {
            id: true,
          },
        },

        code: true,
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [DentalProcedure] })
  @ApiNestedQuery(DentalProcedureFindManyArgs)
  async dentalProcedures(
    @common.Req() request: Request
  ): Promise<DentalProcedure[]> {
    const args = plainToClass(DentalProcedureFindManyArgs, request.query);
    return this.service.dentalProcedures({
      ...args,
      select: {
        active: true,
        basePrice: true,

        clinic: {
          select: {
            id: true,
          },
        },

        code: true,
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: DentalProcedure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async dentalProcedure(
    @common.Param() params: DentalProcedureWhereUniqueInput
  ): Promise<DentalProcedure | null> {
    const result = await this.service.dentalProcedure({
      where: params,
      select: {
        active: true,
        basePrice: true,

        clinic: {
          select: {
            id: true,
          },
        },

        code: true,
        createdAt: true,
        description: true,
        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: DentalProcedure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDentalProcedure(
    @common.Param() params: DentalProcedureWhereUniqueInput,
    @common.Body() data: DentalProcedureUpdateInput
  ): Promise<DentalProcedure | null> {
    try {
      return await this.service.updateDentalProcedure({
        where: params,
        data: {
          ...data,

          clinic: {
            connect: data.clinic,
          },
        },
        select: {
          active: true,
          basePrice: true,

          clinic: {
            select: {
              id: true,
            },
          },

          code: true,
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: DentalProcedure })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDentalProcedure(
    @common.Param() params: DentalProcedureWhereUniqueInput
  ): Promise<DentalProcedure | null> {
    try {
      return await this.service.deleteDentalProcedure({
        where: params,
        select: {
          active: true,
          basePrice: true,

          clinic: {
            select: {
              id: true,
            },
          },

          code: true,
          createdAt: true,
          description: true,
          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/dentalProcedurePrice")
  @ApiNestedQuery(DentalProcedurePriceFindManyArgs)
  async findDentalProcedurePrice(
    @common.Req() request: Request,
    @common.Param() params: DentalProcedureWhereUniqueInput
  ): Promise<DentalProcedurePrice[]> {
    const query = plainToClass(DentalProcedurePriceFindManyArgs, request.query);
    const results = await this.service.findDentalProcedurePrice(params.id, {
      ...query,
      select: {
        createdAt: true,

        dentalProcedure: {
          select: {
            id: true,
          },
        },

        healthInsurance: {
          select: {
            id: true,
          },
        },

        id: true,
        price: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dentalProcedurePrice")
  async connectDentalProcedurePrice(
    @common.Param() params: DentalProcedureWhereUniqueInput,
    @common.Body() body: DentalProcedurePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedurePrice: {
        connect: body,
      },
    };
    await this.service.updateDentalProcedure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dentalProcedurePrice")
  async updateDentalProcedurePrice(
    @common.Param() params: DentalProcedureWhereUniqueInput,
    @common.Body() body: DentalProcedurePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedurePrice: {
        set: body,
      },
    };
    await this.service.updateDentalProcedure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dentalProcedurePrice")
  async disconnectDentalProcedurePrice(
    @common.Param() params: DentalProcedureWhereUniqueInput,
    @common.Body() body: DentalProcedurePriceWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dentalProcedurePrice: {
        disconnect: body,
      },
    };
    await this.service.updateDentalProcedure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/invoiceItem")
  @ApiNestedQuery(InvoiceItemFindManyArgs)
  async findInvoiceItem(
    @common.Req() request: Request,
    @common.Param() params: DentalProcedureWhereUniqueInput
  ): Promise<InvoiceItem[]> {
    const query = plainToClass(InvoiceItemFindManyArgs, request.query);
    const results = await this.service.findInvoiceItem(params.id, {
      ...query,
      select: {
        createdAt: true,

        dentalProcedure: {
          select: {
            id: true,
          },
        },

        id: true,

        invoice: {
          select: {
            id: true,
          },
        },

        quantity: true,
        total: true,

        treatment: {
          select: {
            id: true,
          },
        },

        unitPrice: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/invoiceItem")
  async connectInvoiceItem(
    @common.Param() params: DentalProcedureWhereUniqueInput,
    @common.Body() body: InvoiceItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoiceItem: {
        connect: body,
      },
    };
    await this.service.updateDentalProcedure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/invoiceItem")
  async updateInvoiceItem(
    @common.Param() params: DentalProcedureWhereUniqueInput,
    @common.Body() body: InvoiceItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoiceItem: {
        set: body,
      },
    };
    await this.service.updateDentalProcedure({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/invoiceItem")
  async disconnectInvoiceItem(
    @common.Param() params: DentalProcedureWhereUniqueInput,
    @common.Body() body: InvoiceItemWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      invoiceItem: {
        disconnect: body,
      },
    };
    await this.service.updateDentalProcedure({
      where: params,
      data,
      select: { id: true },
    });
  }
}
