/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { DentalProcedure } from "./DentalProcedure";
import { DentalProcedureCountArgs } from "./DentalProcedureCountArgs";
import { DentalProcedureFindManyArgs } from "./DentalProcedureFindManyArgs";
import { DentalProcedureFindUniqueArgs } from "./DentalProcedureFindUniqueArgs";
import { CreateDentalProcedureArgs } from "./CreateDentalProcedureArgs";
import { UpdateDentalProcedureArgs } from "./UpdateDentalProcedureArgs";
import { DeleteDentalProcedureArgs } from "./DeleteDentalProcedureArgs";
import { DentalProcedurePriceFindManyArgs } from "../../dentalProcedurePrice/base/DentalProcedurePriceFindManyArgs";
import { DentalProcedurePrice } from "../../dentalProcedurePrice/base/DentalProcedurePrice";
import { InvoiceItemFindManyArgs } from "../../invoiceItem/base/InvoiceItemFindManyArgs";
import { InvoiceItem } from "../../invoiceItem/base/InvoiceItem";
import { Clinic } from "../../clinic/base/Clinic";
import { DentalProcedureService } from "../dentalProcedure.service";
@graphql.Resolver(() => DentalProcedure)
export class DentalProcedureResolverBase {
  constructor(protected readonly service: DentalProcedureService) {}

  async _dentalProceduresMeta(
    @graphql.Args() args: DentalProcedureCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [DentalProcedure])
  async dentalProcedures(
    @graphql.Args() args: DentalProcedureFindManyArgs
  ): Promise<DentalProcedure[]> {
    return this.service.dentalProcedures(args);
  }

  @graphql.Query(() => DentalProcedure, { nullable: true })
  async dentalProcedure(
    @graphql.Args() args: DentalProcedureFindUniqueArgs
  ): Promise<DentalProcedure | null> {
    const result = await this.service.dentalProcedure(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => DentalProcedure)
  async createDentalProcedure(
    @graphql.Args() args: CreateDentalProcedureArgs
  ): Promise<DentalProcedure> {
    return await this.service.createDentalProcedure({
      ...args,
      data: {
        ...args.data,

        clinic: {
          connect: args.data.clinic,
        },
      },
    });
  }

  @graphql.Mutation(() => DentalProcedure)
  async updateDentalProcedure(
    @graphql.Args() args: UpdateDentalProcedureArgs
  ): Promise<DentalProcedure | null> {
    try {
      return await this.service.updateDentalProcedure({
        ...args,
        data: {
          ...args.data,

          clinic: {
            connect: args.data.clinic,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DentalProcedure)
  async deleteDentalProcedure(
    @graphql.Args() args: DeleteDentalProcedureArgs
  ): Promise<DentalProcedure | null> {
    try {
      return await this.service.deleteDentalProcedure(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [DentalProcedurePrice], {
    name: "dentalProcedurePrice",
  })
  async findDentalProcedurePrice(
    @graphql.Parent() parent: DentalProcedure,
    @graphql.Args() args: DentalProcedurePriceFindManyArgs
  ): Promise<DentalProcedurePrice[]> {
    const results = await this.service.findDentalProcedurePrice(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => [InvoiceItem], { name: "invoiceItem" })
  async findInvoiceItem(
    @graphql.Parent() parent: DentalProcedure,
    @graphql.Args() args: InvoiceItemFindManyArgs
  ): Promise<InvoiceItem[]> {
    const results = await this.service.findInvoiceItem(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @graphql.ResolveField(() => Clinic, {
    nullable: true,
    name: "clinic",
  })
  async getClinic(
    @graphql.Parent() parent: DentalProcedure
  ): Promise<Clinic | null> {
    const result = await this.service.getClinic(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
