/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsOptional,
  IsNumber,
  Max,
  ValidateNested,
  IsString,
  MaxLength,
  IsDate,
} from "class-validator";

import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";
import { Type } from "class-transformer";
import { DentalProcedurePriceUpdateManyWithoutDentalProceduresInput } from "./DentalProcedurePriceUpdateManyWithoutDentalProceduresInput";
import { InvoiceItemUpdateManyWithoutDentalProceduresInput } from "./InvoiceItemUpdateManyWithoutDentalProceduresInput";

@InputType()
class DentalProcedureUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  active?: boolean;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  basePrice?: number;

  @ApiProperty({
    required: false,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @IsOptional()
  @Field(() => ClinicWhereUniqueInput, {
    nullable: true,
  })
  clinic?: ClinicWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  code?: string;

  @ApiProperty({
    required: false,
    type: () => DentalProcedurePriceUpdateManyWithoutDentalProceduresInput,
  })
  @ValidateNested()
  @Type(() => DentalProcedurePriceUpdateManyWithoutDentalProceduresInput)
  @IsOptional()
  @Field(() => DentalProcedurePriceUpdateManyWithoutDentalProceduresInput, {
    nullable: true,
  })
  dentalProcedurePrice?: DentalProcedurePriceUpdateManyWithoutDentalProceduresInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceItemUpdateManyWithoutDentalProceduresInput,
  })
  @ValidateNested()
  @Type(() => InvoiceItemUpdateManyWithoutDentalProceduresInput)
  @IsOptional()
  @Field(() => InvoiceItemUpdateManyWithoutDentalProceduresInput, {
    nullable: true,
  })
  invoiceItem?: InvoiceItemUpdateManyWithoutDentalProceduresInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  updatedAt?: Date;
}

export { DentalProcedureUpdateInput as DentalProcedureUpdateInput };
