/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsNumber,
  Max,
  ValidateNested,
  IsString,
  MaxLength,
  IsDate,
  IsOptional,
  IsInt,
} from "class-validator";

import { Clinic } from "../../clinic/base/Clinic";
import { Type } from "class-transformer";
import { DentalProcedurePrice } from "../../dentalProcedurePrice/base/DentalProcedurePrice";
import { InvoiceItem } from "../../invoiceItem/base/InvoiceItem";

@ObjectType()
class DentalProcedure {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  active!: boolean;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  basePrice!: number;

  @ApiProperty({
    required: true,
    type: () => Clinic,
  })
  @ValidateNested()
  @Type(() => Clinic)
  clinic?: Clinic;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  code!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: false,
    type: () => [DentalProcedurePrice],
  })
  @ValidateNested()
  @Type(() => DentalProcedurePrice)
  @IsOptional()
  dentalProcedurePrice?: Array<DentalProcedurePrice>;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description!: string | null;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsInt()
  @Field(() => Number)
  id!: number;

  @ApiProperty({
    required: false,
    type: () => [InvoiceItem],
  })
  @ValidateNested()
  @Type(() => InvoiceItem)
  @IsOptional()
  invoiceItem?: Array<InvoiceItem>;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { DentalProcedure as DentalProcedure };
