/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  DentalProcedure as PrismaDentalProcedure,
  DentalProcedurePrice as PrismaDentalProcedurePrice,
  InvoiceItem as PrismaInvoiceItem,
  Clinic as PrismaClinic,
} from "@prisma/client";

export class DentalProcedureServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.DentalProcedureCountArgs, "select">
  ): Promise<number> {
    return this.prisma.dentalProcedure.count(args);
  }

  async dentalProcedures(
    args: Prisma.DentalProcedureFindManyArgs
  ): Promise<PrismaDentalProcedure[]> {
    return this.prisma.dentalProcedure.findMany(args);
  }
  async dentalProcedure(
    args: Prisma.DentalProcedureFindUniqueArgs
  ): Promise<PrismaDentalProcedure | null> {
    return this.prisma.dentalProcedure.findUnique(args);
  }
  async createDentalProcedure(
    args: Prisma.DentalProcedureCreateArgs
  ): Promise<PrismaDentalProcedure> {
    return this.prisma.dentalProcedure.create(args);
  }
  async updateDentalProcedure(
    args: Prisma.DentalProcedureUpdateArgs
  ): Promise<PrismaDentalProcedure> {
    return this.prisma.dentalProcedure.update(args);
  }
  async deleteDentalProcedure(
    args: Prisma.DentalProcedureDeleteArgs
  ): Promise<PrismaDentalProcedure> {
    return this.prisma.dentalProcedure.delete(args);
  }

  async findDentalProcedurePrice(
    parentId: number,
    args: Prisma.DentalProcedurePriceFindManyArgs
  ): Promise<PrismaDentalProcedurePrice[]> {
    return this.prisma.dentalProcedure
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .dentalProcedurePrice(args);
  }

  async findInvoiceItem(
    parentId: number,
    args: Prisma.InvoiceItemFindManyArgs
  ): Promise<PrismaInvoiceItem[]> {
    return this.prisma.dentalProcedure
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .invoiceItem(args);
  }

  async getClinic(parentId: number): Promise<PrismaClinic | null> {
    return this.prisma.dentalProcedure
      .findUnique({
        where: { id: parentId },
      })
      .clinic();
  }
}
