/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";

import {
  IsBoolean,
  IsNumber,
  Max,
  ValidateNested,
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
} from "class-validator";

import { ClinicWhereUniqueInput } from "../../clinic/base/ClinicWhereUniqueInput";
import { Type } from "class-transformer";
import { DentalProcedurePriceCreateNestedManyWithoutDentalProceduresInput } from "./DentalProcedurePriceCreateNestedManyWithoutDentalProceduresInput";
import { InvoiceItemCreateNestedManyWithoutDentalProceduresInput } from "./InvoiceItemCreateNestedManyWithoutDentalProceduresInput";

@InputType()
class DentalProcedureCreateInput {
  @ApiProperty({
    required: true,
    type: Boolean,
  })
  @IsBoolean()
  @Field(() => Boolean)
  active!: boolean;

  @ApiProperty({
    required: true,
    type: Number,
  })
  @IsNumber()
  @Max(99999999999)
  @Field(() => Number)
  basePrice!: number;

  @ApiProperty({
    required: true,
    type: () => ClinicWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => ClinicWhereUniqueInput)
  @Field(() => ClinicWhereUniqueInput)
  clinic!: ClinicWhereUniqueInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  code!: string;

  @ApiProperty({
    required: false,
    type: () =>
      DentalProcedurePriceCreateNestedManyWithoutDentalProceduresInput,
  })
  @ValidateNested()
  @Type(() => DentalProcedurePriceCreateNestedManyWithoutDentalProceduresInput)
  @IsOptional()
  @Field(
    () => DentalProcedurePriceCreateNestedManyWithoutDentalProceduresInput,
    {
      nullable: true,
    }
  )
  dentalProcedurePrice?: DentalProcedurePriceCreateNestedManyWithoutDentalProceduresInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
    type: () => InvoiceItemCreateNestedManyWithoutDentalProceduresInput,
  })
  @ValidateNested()
  @Type(() => InvoiceItemCreateNestedManyWithoutDentalProceduresInput)
  @IsOptional()
  @Field(() => InvoiceItemCreateNestedManyWithoutDentalProceduresInput, {
    nullable: true,
  })
  invoiceItem?: InvoiceItemCreateNestedManyWithoutDentalProceduresInput;

  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @MaxLength(256)
  @Field(() => String)
  name!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;
}

export { DentalProcedureCreateInput as DentalProcedureCreateInput };
